# Generated by Django 6.0.2 on 2026-03-05 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'tarmor_assettype',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ComponentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('short_code', models.CharField(max_length=5, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Component Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EQ_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Equipment_Type', models.CharField(max_length=50)),
                ('Prefix', models.CharField(max_length=10)),
                ('Asset_Type', models.ForeignKey(db_column='Asset_Type', on_delete=django.db.models.deletion.CASCADE, related_name='equipment_types', to='equipment.assettype')),
            ],
            options={
                'db_table': 'tarmor_eq_type',
                'managed': True,
                'unique_together': {('Asset_Type', 'Equipment_Type')},
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Equipment_Number', models.CharField(max_length=20, unique=True)),
                ('Equipment_Status', models.CharField(max_length=50)),
                ('Equipment_Description', models.CharField(blank=True, max_length=255)),
                ('Commissioning_Date', models.DateField(blank=True, null=True)),
                ('Decommissioning_Date', models.DateField(blank=True, null=True)),
                ('Make', models.CharField(blank=True, max_length=50)),
                ('Model', models.CharField(blank=True, max_length=50)),
                ('Serial_Number', models.CharField(blank=True, max_length=50)),
                ('PO_Number', models.CharField(blank=True, max_length=50)),
                ('Equipment_Value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('Warranty_Start_Date', models.DateField(blank=True, null=True)),
                ('Warranty_End_Date', models.DateField(blank=True, null=True)),
                ('Engine_HP_Rating', models.IntegerField(blank=True, null=True)),
                ('CANMET_Number', models.CharField(blank=True, max_length=50)),
                ('Ventilation_Rating', models.CharField(blank=True, max_length=50)),
                ('Responsible_Garage', models.CharField(blank=True, max_length=50)),
                ('Additional_Information', models.TextField(blank=True)),
                ('Asset_Type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipment.assettype')),
                ('Equipment_Type', models.ForeignKey(db_column='Equipment_Type', on_delete=django.db.models.deletion.PROTECT, to='equipment.eq_type')),
            ],
            options={
                'db_table': 'tarmor_equipment',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Component_Number', models.CharField(max_length=50, unique=True)),
                ('Make', models.CharField(blank=True, max_length=50)),
                ('Model', models.CharField(blank=True, max_length=50)),
                ('Serial_Number', models.CharField(blank=True, max_length=50)),
                ('Expected_Lifespan', models.IntegerField(blank=True, null=True)),
                ('UoM', models.CharField(choices=[('Hours', 'Hours'), ('Kms', 'Kms'), ('Cycles', 'Cycles'), ('Years', 'Years')], default='Hours', max_length=10)),
                ('PO_Number', models.CharField(blank=True, max_length=50)),
                ('Warranty_Duration', models.IntegerField(blank=True, null=True)),
                ('Wty_UoM', models.CharField(choices=[('Hours', 'Hours'), ('Kms', 'Kms'), ('Cycles', 'Cycles'), ('Years', 'Years')], default='Hours', max_length=10)),
                ('Warranty_Start_Date', models.DateField(blank=True, null=True)),
                ('Warranty_End_Date', models.DateField(blank=True, null=True)),
                ('Additional_Information', models.TextField(blank=True)),
                ('Component_Type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipment.componenttype')),
                ('Equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='equipment.equipment')),
            ],
            options={
                'db_table': 'tarmor_component',
            },
        ),
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_type', models.CharField(choices=[('', 'Select'), ('Engine Hours', 'Engine Hours'), ('Odometer', 'Odometer'), ('Power Pack Hours', 'Power Pack Hours'), ('Power Pack Left', 'Power Pack Left'), ('Power Pack Right', 'Power Pack Right'), ('Impact Hours', 'Impact Hours'), ('Impact Left', 'Impact Left'), ('Impact Right', 'Impact Right'), ('Operating Hours', 'Operating Hours')], max_length=50)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meters', to='equipment.equipment')),
            ],
            options={
                'db_table': 'tarmor_meter',
            },
        ),
    ]
