# Generated by Django 6.0.2 on 2026-03-05 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='Installation_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='component',
            name='Removal_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='component',
            name='Status',
            field=models.CharField(choices=[('Installed', 'Installed'), ('Spare', 'Spare'), ('Retired', 'Retired')], default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='componenttype',
            name='asset_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='component_types', to='equipment.assettype'),
            preserve_default=False,
        ),
    ]
