# Generated by Django 6.0.2 on 2026-03-06 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_component_installation_date_component_removal_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componenttype',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='componenttype',
            name='short_code',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterUniqueTogether(
            name='componenttype',
            unique_together={('name', 'asset_type'), ('short_code', 'asset_type')},
        ),
    ]
