# Generated by Django 6.0.2 on 2026-03-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_alter_componenttype_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='Component_Description',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
