# Generated by Django 6.0.2 on 2026-03-07 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_component_component_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='Component_Description',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='ComponentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Work_Order_Number', models.CharField(max_length=50)),
                ('Change_Date', models.DateField()),
                ('Change_Type', models.CharField(choices=[('Replaced New', 'Replaced New'), ('Replaced Reman', 'Replaced Reman'), ('Rebuilt', 'Rebuilt')], max_length=50)),
                ('Meter_Description', models.CharField(max_length=50)),
                ('Meter_Reading', models.DecimalField(decimal_places=0, max_digits=12)),
                ('Old_Serial', models.CharField(max_length=50)),
                ('New_Serial', models.CharField(max_length=50)),
                ('New_Make', models.CharField(max_length=50)),
                ('New_Model', models.CharField(max_length=50)),
                ('Additional_Information', models.TextField(blank=True)),
                ('Date_Recorded', models.DateTimeField(auto_now_add=True)),
                ('Component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='equipment.component')),
                ('Equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.equipment')),
            ],
            options={
                'db_table': 'tarmor_component_history',
                'ordering': ['-Change_Date'],
            },
        ),
    ]
