# Generated by Django 6.0.2 on 2026-03-08 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0006_componenthistory_new_lifespan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shift', models.CharField(choices=[('DS', 'Day Shift'), ('NS', 'Night Shift')], max_length=2)),
                ('mining_supervisor', models.CharField(max_length=100)),
                ('maint_supervisor', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hourly_data', models.JSONField(default=dict)),
            ],
            options={
                'unique_together': {('date', 'shift')},
            },
        ),
        migrations.CreateModel(
            name='MachineShiftStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_down', models.FloatField(default=0.0)),
                ('available', models.FloatField(default=11.0)),
                ('final_status', models.CharField(choices=[('Y', 'Available'), ('N', 'Down')], max_length=1)),
                ('grid_data', models.TextField(help_text='Comma-separated D, P, or empty values')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.equipment')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='equipment.shiftreport')),
            ],
        ),
    ]
