# Generated by Django 6.0.2 on 2026-03-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0007_shiftreport_machineshiftstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='End_of_Life',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='Overhaul_Period',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='Overhaul_Value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
