# Generated by Django 6.0.2 on 2026-03-13 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0008_equipment_end_of_life_equipment_overhaul_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='End_of_Life',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='Overhaul_Period',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='machineshiftstatus',
            name='final_status',
            field=models.CharField(choices=[('Available', 'Available'), ('Down', 'Down')], max_length=10),
        ),
    ]
