# Generated by Django 6.0.2 on 2026-04-09 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0009_alter_equipment_end_of_life_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='Equipment',
            field=models.ForeignKey(db_column='Equipment_Number', on_delete=django.db.models.deletion.CASCADE, related_name='components', to='equipment.equipment'),
        ),
    ]
