# Generated by Django 6.0.2 on 2026-04-12 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0010_alter_component_equipment'),
        ('facilities', '0003_rename_street_address_1_facility_street_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftreport',
            name='asset_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.assettype'),
        ),
        migrations.AddField(
            model_name='shiftreport',
            name='responsible_garage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_reports', to='facilities.facility'),
        ),
    ]
