# Generated by Django 6.0.2 on 2026-04-12 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0011_shiftreport_asset_type_and_more'),
        ('facilities', '0003_rename_street_address_1_facility_street_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shiftreport',
            old_name='responsible_garage',
            new_name='garage',
        ),
        migrations.AddField(
            model_name='equipment',
            name='Garage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facilities.facility', to_field='Facility_Name'),
        ),
    ]
