# Generated by Django 6.0.2 on 2026-04-12 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0012_rename_responsible_garage_shiftreport_garage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='Responsible_Garage',
        ),
    ]
