# Generated by Django 6.0.2 on 2026-04-15 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0013_remove_equipment_responsible_garage'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='Box_Type',
            field=models.CharField(blank=True, choices=[('Dump', 'Dump'), ('Ejector', 'Ejector')], null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='Cab_Style',
            field=models.CharField(blank=True, choices=[('Open', 'Open'), ('Enclosed', 'Enclosed')], null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='Eng_Tier',
            field=models.CharField(blank=True, choices=[('N/A', 'N/A'), ('Tier 2', 'Tier 2'), ('Tier 3', 'Tier 3'), ('Tier 4', 'Tier 4')], null=True),
        ),
    ]
