# Generated by Django 6.0.2 on 2026-04-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0014_equipment_box_type_equipment_cab_style_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machineshiftstatus',
            name='total_worked',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='machineshiftstatus',
            name='grid_data',
            field=models.TextField(help_text='Comma-separated D, W, P, or empty values'),
        ),
    ]
