# Generated by Django 6.0.2 on 2026-04-16 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0015_machineshiftstatus_total_worked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineshiftstatus',
            name='available',
            field=models.FloatField(default=12.0),
        ),
    ]
