# Generated by Django 6.0.4 on 2026-05-01 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0016_alter_machineshiftstatus_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='Equipment_Image',
            field=models.ImageField(blank=True, null=True, upload_to='equipment_pics/'),
        ),
    ]
