# Generated by Django 6.0.4 on 2026-05-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0017_equipment_equipment_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='Component_Image',
            field=models.ImageField(blank=True, null=True, upload_to='equipment_pics/'),
        ),
    ]
