# Generated by Django 6.0.4 on 2026-05-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0018_component_component_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='Wty_UoM',
            field=models.CharField(choices=[('Hours', 'Hours'), ('Kms', 'Kms'), ('Cycles', 'Cycles'), ('Years', 'Years'), ('Months', 'Months')], default='Hours', max_length=10),
        ),
    ]
