# Generated by Django 6.0.4 on 2026-05-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0019_alter_component_wty_uom'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='eol_uom',
            field=models.CharField(blank=True, choices=[('hrs', 'hrs'), ('yrs', 'yrs'), ('kms', 'kms')], null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='oh_uom',
            field=models.CharField(blank=True, choices=[('hrs', 'hrs'), ('yrs', 'yrs'), ('kms', 'kms')], null=True),
        ),
    ]
