# Generated by Django 6.0.4 on 2026-05-25 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0020_equipment_eol_uom_equipment_oh_uom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='End_of_Life',
            field=models.IntegerField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='Overhaul_Period',
            field=models.IntegerField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='eol_uom',
            field=models.CharField(blank=True, choices=[('hrs', 'hrs'), ('yrs', 'yrs'), ('kms', 'kms')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='oh_uom',
            field=models.CharField(blank=True, choices=[('hrs', 'hrs'), ('yrs', 'yrs'), ('kms', 'kms')], max_length=3, null=True),
        ),
    ]
