# Generated by Django 6.0.4 on 2026-05-25 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0021_alter_equipment_end_of_life_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='End_of_Life',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='Overhaul_Period',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
