# Generated by Django 6.0.4 on 2026-05-25 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0022_alter_equipment_end_of_life_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='Status',
            field=models.CharField(choices=[('Installed', 'Installed'), ('Spare', 'Spare'), ('Retired', 'Retired')], default='Installed', max_length=20),
        ),
    ]
