# Generated by Django 6.0.4 on 2026-05-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0023_alter_component_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='eol_uom',
            field=models.CharField(blank=True, choices=[('', 'Select'), ('Engine Hours', 'Engine Hours'), ('Odometer', 'Odometer'), ('Power Pack Hours', 'Power Pack Hours'), ('Power Pack Left', 'Power Pack Left'), ('Power Pack Right', 'Power Pack Right'), ('Impact Hours', 'Impact Hours'), ('Impact Left', 'Impact Left'), ('Impact Right', 'Impact Right'), ('Operating Hours', 'Operating Hours')], null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='oh_uom',
            field=models.CharField(blank=True, choices=[('', 'Select'), ('Engine Hours', 'Engine Hours'), ('Odometer', 'Odometer'), ('Power Pack Hours', 'Power Pack Hours'), ('Power Pack Left', 'Power Pack Left'), ('Power Pack Right', 'Power Pack Right'), ('Impact Hours', 'Impact Hours'), ('Impact Left', 'Impact Left'), ('Impact Right', 'Impact Right'), ('Operating Hours', 'Operating Hours')], null=True),
        ),
    ]
