# Generated by Django 6.0.4 on 2026-05-29 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_name', models.CharField(max_length=50)),
                ('action_key', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='FailureType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failure_mode', models.CharField(max_length=50)),
                ('failure_code', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_key', models.CharField(choices=[('', 'Select'), ('F', 'F'), ('M', 'M')], max_length=1)),
                ('system_name', models.CharField(max_length=50)),
                ('system_key', models.CharField(max_length=3)),
                ('combined_sys_key', models.CharField(max_length=4, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_name', models.CharField(max_length=50)),
                ('component_key', models.CharField(max_length=4)),
                ('combined_comp_key', models.CharField(max_length=8, unique=True)),
                ('combined_sys_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='failures.system')),
            ],
        ),
    ]
