# Generated by Django 6.0.2 on 2026-04-02 13:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0004_delete_purchaserequest'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_type', models.CharField(choices=[('P', 'Purchase Order'), ('R', 'Purchase Requisition'), ('S', 'Service')], max_length=20)),
                ('purchase_number', models.CharField(max_length=10)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('bill_location', models.CharField(choices=[('Work Order', 'Work Order'), ('General Acc', 'General Acc')], max_length=30)),
                ('wo_cc', models.CharField(max_length=10)),
                ('qty', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Received', 'Received'), ('Cancelled', 'Cancelled'), ('Returned', 'Returned'), ('Paid', 'Paid')], default='Pending', max_length=10)),
                ('additional_information', models.TextField(blank=True, null=True)),
                ('part_description', models.ForeignKey(db_column='part_description', on_delete=django.db.models.deletion.PROTECT, related_name='purch_part_description', to='inventory.inventoryitem')),
                ('part_number', models.ForeignKey(db_column='part_number', on_delete=django.db.models.deletion.PROTECT, related_name='purch_part_number', to='inventory.inventoryitem')),
                ('supplier', models.ForeignKey(db_column='supplier_name', on_delete=django.db.models.deletion.PROTECT, related_name='purch_supplier', to='suppliers.supplier')),
                ('uom', models.ForeignKey(db_column='uom', on_delete=django.db.models.deletion.PROTECT, related_name='purch_uom', to='inventory.inventoryitem')),
            ],
        ),
    ]
