# Generated by Django 6.0.2 on 2026-04-03 14:08

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_delete_purchaserequest'),
        ('purchasing', '0002_purchase_grand_total'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='part_description',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='part_number',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='qty',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='unit_price',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='uom',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='bill_location',
            field=models.CharField(choices=[('Work Order', 'Work Order'), ('Cost Centre', 'Cost Centre')], max_length=20),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_number',
            field=models.CharField(blank=True, max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_type',
            field=models.CharField(choices=[('P', 'Purchase Order'), ('R', 'Purchase Requisition'), ('S', 'Service Order')], max_length=1),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='wo_cc',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='PurchaseLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manual_part_number', models.CharField(blank=True, max_length=100)),
                ('part_description', models.CharField(blank=True, max_length=255)),
                ('uom', models.CharField(blank=True, max_length=30)),
                ('qty', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12)),
                ('row_status', models.CharField(choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Received', 'Received'), ('Cancelled', 'Cancelled'), ('Returned', 'Returned'), ('Paid', 'Paid')], default='Pending', max_length=10)),
                ('part_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_lines', to='inventory.inventoryitem')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchasing.purchase')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_lines', to='suppliers.supplier')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
