# Generated by Django 6.0.2 on 2026-04-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0003_alter_purchase_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='barcode_image',
            field=models.ImageField(blank=True, editable=False, upload_to='barcodes/'),
        ),
    ]
