# Generated by Django 6.0.2 on 2026-04-13 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_delete_purchaserequest'),
        ('purchasing', '0004_purchase_barcode_image'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseline',
            options={},
        ),
        migrations.RemoveField(
            model_name='purchaseline',
            name='part_number',
        ),
        migrations.AddField(
            model_name='purchaseline',
            name='inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='purchaseline',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='purchaseline',
            name='part_number_input',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchaseline',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.supplier'),
        ),
    ]
