# Generated by Django 6.0.4 on 2026-05-06 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_workorder_project_and_more'),
        ('purchasing', '0005_alter_purchaseline_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='projects.project'),
        ),
    ]
