# Generated by Django 6.0.4 on 2026-05-29 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        ('personnel', '0001_initial'),
        ('work_orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Monday', max_length=10)),
                ('week1_start_date', models.DateField(verbose_name='Start Date for Week 1')),
                ('active', models.BooleanField(default=True, help_text='Only one active setup should exist at a time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locked', models.BooleanField(default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('last_saved', models.DateTimeField(auto_now=True)),
                ('responsible_garage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facilities.facility', verbose_name='Garage')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_start_snapshot', models.DateField()),
                ('estimated_hours_snapshot', models.DecimalField(decimal_places=2, max_digits=6)),
                ('job_status_snapshot', models.CharField(max_length=50)),
                ('date_closed_snapshot', models.DateField(blank=True, null=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='scheduling.schedule')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='work_orders.workorder')),
            ],
        ),
        migrations.CreateModel(
            name='WorkWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveSmallIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('setup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='scheduling.weeksetup')),
            ],
            options={
                'ordering': ['week_number'],
                'unique_together': {('setup', 'week_number')},
            },
        ),
        migrations.AddField(
            model_name='schedule',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.workweek'),
        ),
        migrations.CreateModel(
            name='DailyCrewCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('available_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('assigned_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personnel.crew')),
                ('workweek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.workweek')),
            ],
        ),
        migrations.CreateModel(
            name='TimeOffLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ds_off', models.IntegerField(default=0)),
                ('ns_off', models.IntegerField(default=0)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_off_logs', to='facilities.facility')),
            ],
            options={
                'db_table': 'tarmor_time_off_log',
                'unique_together': {('facility', 'date')},
            },
        ),
    ]
