# Generated by Django 6.0.4 on 2026-05-29 15:58

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('moc_number', models.CharField(blank=True, max_length=100)),
                ('assigned_to', models.CharField(blank=True, max_length=100)),
                ('start_year', models.CharField(blank=True, max_length=4)),
                ('execution_time', models.IntegerField(blank=True, default=1, null=True)),
                ('uom', models.CharField(blank=True, default='Years', max_length=20, null=True)),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Deferred', 'Deferred'), ('In-Progress', 'In-Progress'), ('Complete', 'Complete'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('spend', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('remaining', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('scope', models.TextField(blank=True)),
                ('justification', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='project_attachments/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('allocated_budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectFinancial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('jan_p', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('feb_p', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mar_p', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('apr_p', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('may_p', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('jun_p', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('jul_p', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('aug_p', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sep_p', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('oct_p', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('nov_p', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('dec_p', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cost_carryover', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cash_carryover', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financials', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('time_to_implement', models.IntegerField()),
                ('uom', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('step_note', models.CharField(blank=True, max_length=255)),
                ('action', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('progress', models.TextField(blank=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('complete', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='projects.project')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.projectstep')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('failure', models.CharField(blank=True, max_length=255)),
                ('action', models.TextField(blank=True)),
                ('lesson', models.CharField(blank=True, max_length=255)),
                ('progress', models.TextField(blank=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('complete', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='projects.project')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.projectstep')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDelay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delay_type', models.CharField(max_length=100)),
                ('cause', models.CharField(max_length=100)),
                ('time_requirement', models.IntegerField()),
                ('uom', models.CharField(max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delays', to='projects.project')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projectstep')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('tasks', models.CharField(blank=True, max_length=255)),
                ('assignee', models.CharField(blank=True, max_length=255)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('progress', models.TextField(blank=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('complete', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.projectstep')),
            ],
        ),
    ]
