[build]
builder = "NIXPACKS"

[deploy]
startCommand = "gunicorn tarmor_config.wsgi:application --bind 0.0.0.0:$PORT"
preDeployCommand = "python manage.py migrate_schemas --shared && python tarmor_config/create_admins.py"
restartPolicyType = "ON_FAILURE"