# Generated by Django 6.0.4 on 2026-05-29 15:58

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pattern_sequence', models.CharField(help_text='Comma-separated days: 5,5,4,4 (Work 5, Off 5, Work 4, Off 4)', max_length=100)),
                ('is_rotating', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CrewShiftRotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Shift_ID', models.CharField(editable=False, max_length=20, unique=True)),
                ('Coverage_Type', models.CharField(choices=[('24H', '24 Hour Coverage'), ('DS', 'Day Shift Only'), ('NS', 'Night Shift Only')], max_length=3)),
                ('hrs_per_shift', models.CharField(max_length=2)),
                ('shift_start', models.TimeField(blank=True, help_text='Format HH:MM (e.g. 07:00 or 19:00)', null=True)),
                ('Calendar_Month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default='January', max_length=15)),
                ('Start_Date', models.DateField()),
                ('province', models.CharField(choices=[('AB', 'Alberta'), ('BC', 'British Columbia'), ('MB', 'Manitoba'), ('NB', 'New Brunswick'), ('NL', 'Newfoundland and Labrador'), ('NS', 'Nova Scotia'), ('NT', 'Northwest Territories'), ('NU', 'Nunavut'), ('ON', 'Ontario'), ('PE', 'Prince Edward Island'), ('QC', 'Quebec'), ('SK', 'Saskatchewan'), ('YT', 'Yukon')], default='MB', max_length=2)),
                ('batch_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facilities.facility')),
                ('pattern', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='personnel.shiftpattern')),
            ],
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_code', models.CharField(max_length=50)),
                ('shift_letter', models.CharField(max_length=1)),
                ('start_date', models.DateField()),
                ('province', models.CharField(choices=[('AB', 'Alberta'), ('BC', 'British Columbia'), ('MB', 'Manitoba'), ('NB', 'New Brunswick'), ('NL', 'Newfoundland and Labrador'), ('NS', 'Nova Scotia'), ('NT', 'Northwest Territories'), ('NU', 'Nunavut'), ('ON', 'Ontario'), ('PE', 'Prince Edward Island'), ('QC', 'Quebec'), ('SK', 'Saskatchewan'), ('YT', 'Yukon')], default='MB', max_length=2)),
                ('rotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_crews', to='personnel.crewshiftrotation')),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crews', to='personnel.shiftpattern')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=255)),
                ('Middle_Name', models.CharField(blank=True, max_length=255)),
                ('Last_Name', models.CharField(max_length=255)),
                ('Status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=10)),
                ('Position', models.CharField(max_length=255)),
                ('Start_Date', models.DateField(blank=True, null=True)),
                ('Last_Date', models.DateField(blank=True, null=True)),
                ('Street_Address', models.CharField(blank=True, max_length=255, null=True)),
                ('City', models.CharField(blank=True, max_length=100, null=True)),
                ('Prov_State', models.CharField(blank=True, choices=[('AB', 'Alberta'), ('BC', 'British Columbia'), ('MB', 'Manitoba'), ('NB', 'New Brunswick'), ('NL', 'Newfoundland and Labrador'), ('NS', 'Nova Scotia'), ('NT', 'Northwest Territories'), ('NU', 'Nunavut'), ('ON', 'Ontario'), ('PE', 'Prince Edward Island'), ('QC', 'Quebec'), ('SK', 'Saskatchewan'), ('YT', 'Yukon')], max_length=50, null=True)),
                ('Country', models.CharField(blank=True, max_length=100, null=True)),
                ('Postal_Zip', models.CharField(blank=True, max_length=10, null=True)),
                ('Phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Format: '+999999999'", regex='^\\+?1?\\d{9,15}$')])),
                ('Email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('EC_First_Name', models.CharField(max_length=255)),
                ('EC_Middle_Name', models.CharField(blank=True, max_length=255)),
                ('EC_Last_Name', models.CharField(max_length=255)),
                ('EC_Phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Format: '+999999999'", regex='^\\+?1?\\d{9,15}$')])),
                ('EC_Email', models.EmailField(blank=True, max_length=255, null=True)),
                ('Additional_Information', models.TextField(blank=True)),
                ('Employee_Image', models.ImageField(blank=True, null=True, upload_to='employee_pics/')),
                ('crew', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='personnel.crew')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Certification', models.CharField(blank=True, max_length=255, null=True)),
                ('Institution', models.CharField(blank=True, max_length=255, null=True)),
                ('Date_Cert', models.DateField(blank=True, null=True)),
                ('Renewable', models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=6)),
                ('Renewal_Cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='personnel.employee')),
            ],
        ),
    ]
