# Generated by Django 6.0.2 on 2026-03-15 17:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=255)),
                ('Middle_Name', models.CharField(blank=True, max_length=255)),
                ('Last_Name', models.CharField(max_length=255)),
                ('Status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=10)),
                ('Position', models.CharField(max_length=255)),
                ('Compensation', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Comp_UoM', models.CharField(choices=[('hour', 'hour'), ('year', 'year')], max_length=6)),
                ('Location', models.CharField(blank=True, max_length=255)),
                ('Shift', models.CharField(blank=True, max_length=50)),
                ('Start_Date', models.DateField(blank=True, null=True)),
                ('Last_Date', models.DateField(blank=True, null=True)),
                ('Street_Address', models.CharField(blank=True, max_length=255, null=True)),
                ('City', models.CharField(blank=True, max_length=100, null=True)),
                ('Prov_State', models.CharField(blank=True, max_length=50, null=True)),
                ('Country', models.CharField(blank=True, max_length=100, null=True)),
                ('Postal_Zip', models.CharField(blank=True, max_length=10, null=True)),
                ('Phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Format: '+999999999'", regex='^\\+?1?\\d{9,15}$')])),
                ('Email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('EC_First_Name', models.CharField(max_length=255)),
                ('EC_Middle_Name', models.CharField(blank=True, max_length=255)),
                ('EC_Last_Name', models.CharField(max_length=255)),
                ('EC_Phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Format: '+999999999'", regex='^\\+?1?\\d{9,15}$')])),
                ('EC_Email', models.EmailField(blank=True, max_length=255, null=True)),
                ('Additional_Information', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Certification', models.CharField(blank=True, max_length=255, null=True)),
                ('Institution', models.CharField(blank=True, max_length=255, null=True)),
                ('Date_Cert', models.DateField(blank=True, null=True)),
                ('Renewable', models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=6)),
                ('Renewal_Cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='personnel.employee')),
            ],
        ),
    ]
