# Generated by Django 6.0.2 on 2026-03-16 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_code', models.CharField(max_length=50)),
                ('shift_letter', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('start_date', models.DateField(help_text='When this crew begins Day 1 of the cycle')),
                ('province', models.CharField(choices=[('AB', 'Alberta'), ('BC', 'British Columbia'), ('MB', 'Manitoba'), ('NB', 'New Brunswick'), ('NL', 'Newfoundland and Labrador'), ('NS', 'Nova Scotia'), ('NT', 'Northwest Territories'), ('NU', 'Nunavut'), ('ON', 'Ontario'), ('PE', 'Prince Edward Island'), ('QC', 'Quebec'), ('SK', 'Saskatchewan'), ('YT', 'Yukon')], default='MB', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ShiftPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('days_on', models.IntegerField()),
                ('days_off', models.IntegerField()),
                ('coverage_type', models.CharField(choices=[('24H', '24 Hour Coverage'), ('DAY', 'Day Shift Only')], max_length=3)),
                ('is_rotating', models.BooleanField(default=True, help_text='Does this shift rotate between Day/Night?')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='crew',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personnel.crew'),
        ),
        migrations.AddField(
            model_name='crew',
            name='pattern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personnel.shiftpattern'),
        ),
    ]
