# Generated by Django 6.0.2 on 2026-03-17 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
        ('personnel', '0002_crew_shiftpattern_employee_crew_crew_pattern'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrewShiftRotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Shift_ID', models.CharField(editable=False, max_length=20, unique=True)),
                ('Coverage_Type', models.CharField(choices=[('24H', '24 Hour Coverage'), ('DS', 'Day Shift Only'), ('NS', 'Night Shift Only')], max_length=3)),
                ('Start_Date', models.DateField()),
                ('Calendar_Month', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personnel.crew')),
                ('Location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facilities.facility')),
            ],
            options={
                'verbose_name': 'Crew Shift / Rotation',
                'verbose_name_plural': 'Crew Shift / Rotations',
                'ordering': ['Location', 'Shift_ID'],
            },
        ),
    ]
