# Generated by Django 6.0.2 on 2026-03-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0003_crewshiftrotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crewshiftrotation',
            name='Calendar_Month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default='January', max_length=15),
        ),
    ]
