# Generated by Django 6.0.2 on 2026-03-17 19:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0004_alter_crewshiftrotation_calendar_month'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crewshiftrotation',
            options={},
        ),
        migrations.RemoveField(
            model_name='shiftpattern',
            name='coverage_type',
        ),
        migrations.RemoveField(
            model_name='shiftpattern',
            name='days_off',
        ),
        migrations.RemoveField(
            model_name='shiftpattern',
            name='days_on',
        ),
        migrations.AddField(
            model_name='crewshiftrotation',
            name='pattern',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='personnel.shiftpattern'),
        ),
        migrations.AddField(
            model_name='crewshiftrotation',
            name='province',
            field=models.CharField(choices=[('AB', 'Alberta'), ('BC', 'British Columbia'), ('MB', 'Manitoba'), ('NB', 'New Brunswick'), ('NL', 'Newfoundland and Labrador'), ('NS', 'Nova Scotia'), ('NT', 'Northwest Territories'), ('NU', 'Nunavut'), ('ON', 'Ontario'), ('PE', 'Prince Edward Island'), ('QC', 'Quebec'), ('SK', 'Saskatchewan'), ('YT', 'Yukon')], default='MB', max_length=2),
        ),
        migrations.AddField(
            model_name='shiftpattern',
            name='pattern_sequence',
            field=models.CharField(default=django.utils.timezone.now, help_text='Comma-separated days: 5,5,4,4 (Work 5, Off 5, Work 4, Off 4)', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='crew',
            name='pattern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crews', to='personnel.shiftpattern'),
        ),
        migrations.AlterField(
            model_name='crew',
            name='shift_letter',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='crew',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='shiftpattern',
            name='is_rotating',
            field=models.BooleanField(default=True),
        ),
    ]
