# Generated by Django 6.0.2 on 2026-03-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0006_crewshiftrotation_batch_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Shift',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
