# Generated by Django 6.0.2 on 2026-03-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0007_alter_employee_location_alter_employee_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crewshiftrotation',
            name='batch_id',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True),
        ),
    ]
