# Generated by Django 6.0.2 on 2026-03-19 13:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0008_alter_crewshiftrotation_batch_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crewshiftrotation',
            name='batch_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
