# Generated by Django 6.0.2 on 2026-03-19 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0009_alter_crewshiftrotation_batch_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='Location',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='Shift',
        ),
        migrations.AlterField(
            model_name='employee',
            name='crew',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='personnel.crew'),
        ),
    ]
