# Generated by Django 6.0.4 on 2026-04-23 03:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_rename_street_address_1_facility_street_address_and_more'),
        ('personnel', '0011_alter_employee_prov_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_code', models.CharField(max_length=50)),
                ('shift_letter', models.CharField(max_length=1)),
                ('start_date', models.DateField()),
                ('province', models.CharField(choices=[('AB', 'Alberta'), ('BC', 'British Columbia'), ('MB', 'Manitoba'), ('NB', 'New Brunswick'), ('NL', 'Newfoundland and Labrador'), ('NS', 'Nova Scotia'), ('NT', 'Northwest Territories'), ('NU', 'Nunavut'), ('ON', 'Ontario'), ('PE', 'Prince Edward Island'), ('QC', 'Quebec'), ('SK', 'Saskatchewan'), ('YT', 'Yukon')], default='MB', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ShiftPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pattern_sequence', models.CharField(help_text='Comma-separated days: 5,5,4,4 (Work 5, Off 5, Work 4, Off 4)', max_length=100)),
                ('is_rotating', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='Location',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='Shift',
        ),
        migrations.AlterField(
            model_name='employee',
            name='Prov_State',
            field=models.CharField(blank=True, choices=[('AB', 'Alberta'), ('BC', 'British Columbia'), ('MB', 'Manitoba'), ('NB', 'New Brunswick'), ('NL', 'Newfoundland and Labrador'), ('NS', 'Nova Scotia'), ('NT', 'Northwest Territories'), ('NU', 'Nunavut'), ('ON', 'Ontario'), ('PE', 'Prince Edward Island'), ('QC', 'Quebec'), ('SK', 'Saskatchewan'), ('YT', 'Yukon')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='crew',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='personnel.crew'),
        ),
        migrations.CreateModel(
            name='CrewShiftRotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Shift_ID', models.CharField(editable=False, max_length=20, unique=True)),
                ('Coverage_Type', models.CharField(choices=[('24H', '24 Hour Coverage'), ('DS', 'Day Shift Only'), ('NS', 'Night Shift Only')], max_length=3)),
                ('hrs_per_shift', models.CharField(max_length=2)),
                ('shift_start', models.TimeField(blank=True, help_text='Format HH:MM (e.g. 07:00 or 19:00)', null=True)),
                ('Calendar_Month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default='January', max_length=15)),
                ('Start_Date', models.DateField()),
                ('province', models.CharField(choices=[('AB', 'Alberta'), ('BC', 'British Columbia'), ('MB', 'Manitoba'), ('NB', 'New Brunswick'), ('NL', 'Newfoundland and Labrador'), ('NS', 'Nova Scotia'), ('NT', 'Northwest Territories'), ('NU', 'Nunavut'), ('ON', 'Ontario'), ('PE', 'Prince Edward Island'), ('QC', 'Quebec'), ('SK', 'Saskatchewan'), ('YT', 'Yukon')], default='MB', max_length=2)),
                ('batch_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facilities.facility')),
                ('pattern', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='personnel.shiftpattern')),
            ],
        ),
        migrations.AddField(
            model_name='crew',
            name='rotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crews', to='personnel.crewshiftrotation'),
        ),
        migrations.AddField(
            model_name='crew',
            name='pattern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crews', to='personnel.shiftpattern'),
        ),
    ]
