# Generated by Django 6.0.4 on 2026-04-23 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0012_crew_shiftpattern_remove_employee_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew',
            name='rotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_crews', to='personnel.crewshiftrotation'),
        ),
    ]
