# Generated by Django 6.0.4 on 2026-04-24 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0013_alter_crew_rotation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='Comp_UoM',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='Compensation',
        ),
    ]
