# Generated by Django 6.0.4 on 2026-05-03 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0014_remove_employee_comp_uom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Employee_Image',
            field=models.ImageField(blank=True, null=True, upload_to='employee_pics/'),
        ),
    ]
