# Generated by Django 6.0.4 on 2026-05-29 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'tarmor_assettype',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ComponentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_code', models.CharField(max_length=5)),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_types', to='equipment.assettype')),
            ],
            options={
                'verbose_name_plural': 'Component Types',
                'ordering': ['name'],
                'unique_together': {('name', 'asset_type'), ('short_code', 'asset_type')},
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(choices=[('Installed', 'Installed'), ('Spare', 'Spare'), ('Retired', 'Retired')], default='Installed', max_length=20)),
                ('Installation_Date', models.DateField(blank=True, null=True)),
                ('Removal_Date', models.DateField(blank=True, null=True)),
                ('Component_Number', models.CharField(max_length=50, unique=True)),
                ('Component_Description', models.CharField(max_length=100)),
                ('Make', models.CharField(blank=True, max_length=50)),
                ('Model', models.CharField(blank=True, max_length=50)),
                ('Serial_Number', models.CharField(blank=True, max_length=50)),
                ('Expected_Lifespan', models.IntegerField(blank=True, null=True)),
                ('UoM', models.CharField(choices=[('Hours', 'Hours'), ('Kms', 'Kms'), ('Cycles', 'Cycles'), ('Years', 'Years')], default='Hours', max_length=10)),
                ('PO_Number', models.CharField(blank=True, max_length=50)),
                ('Warranty_Duration', models.IntegerField(blank=True, null=True)),
                ('Wty_UoM', models.CharField(choices=[('Hours', 'Hours'), ('Kms', 'Kms'), ('Cycles', 'Cycles'), ('Years', 'Years'), ('Months', 'Months')], default='Hours', max_length=10)),
                ('Warranty_Start_Date', models.DateField(blank=True, null=True)),
                ('Warranty_End_Date', models.DateField(blank=True, null=True)),
                ('Additional_Information', models.TextField(blank=True)),
                ('Component_Image', models.ImageField(blank=True, null=True, upload_to='equipment_pics/')),
                ('Component_Type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipment.componenttype')),
            ],
            options={
                'db_table': 'tarmor_component',
            },
        ),
        migrations.CreateModel(
            name='EQ_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Equipment_Type', models.CharField(max_length=50)),
                ('Prefix', models.CharField(max_length=10)),
                ('Asset_Type', models.ForeignKey(db_column='Asset_Type', on_delete=django.db.models.deletion.CASCADE, related_name='equipment_types', to='equipment.assettype')),
            ],
            options={
                'db_table': 'tarmor_eq_type',
                'managed': True,
                'unique_together': {('Asset_Type', 'Equipment_Type')},
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Equipment_Number', models.CharField(max_length=20, unique=True)),
                ('Equipment_Status', models.CharField(max_length=50)),
                ('Equipment_Description', models.CharField(blank=True, max_length=255)),
                ('Commissioning_Date', models.DateField(blank=True, null=True)),
                ('Decommissioning_Date', models.DateField(blank=True, null=True)),
                ('Make', models.CharField(blank=True, max_length=50)),
                ('Model', models.CharField(blank=True, max_length=50)),
                ('Serial_Number', models.CharField(blank=True, max_length=50)),
                ('PO_Number', models.CharField(blank=True, max_length=50)),
                ('Equipment_Value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('Warranty_Start_Date', models.DateField(blank=True, null=True)),
                ('Warranty_End_Date', models.DateField(blank=True, null=True)),
                ('Engine_HP_Rating', models.IntegerField(blank=True, null=True)),
                ('CANMET_Number', models.CharField(blank=True, max_length=50)),
                ('Ventilation_Rating', models.CharField(blank=True, max_length=50)),
                ('Overhaul_Period', models.IntegerField(blank=True, null=True)),
                ('oh_uom', models.CharField(blank=True, choices=[('', 'Select'), ('Engine Hours', 'Engine Hours'), ('Odometer', 'Odometer'), ('Power Pack Hours', 'Power Pack Hours'), ('Power Pack Left', 'Power Pack Left'), ('Power Pack Right', 'Power Pack Right'), ('Impact Hours', 'Impact Hours'), ('Impact Left', 'Impact Left'), ('Impact Right', 'Impact Right'), ('Operating Hours', 'Operating Hours'), ('Calendar Years', 'Calendar Years')], null=True)),
                ('Overhaul_Value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('End_of_Life', models.IntegerField(blank=True, null=True)),
                ('Cab_Style', models.CharField(blank=True, choices=[('Open', 'Open'), ('Enclosed', 'Enclosed')], null=True)),
                ('eol_uom', models.CharField(blank=True, choices=[('', 'Select'), ('Engine Hours', 'Engine Hours'), ('Odometer', 'Odometer'), ('Power Pack Hours', 'Power Pack Hours'), ('Power Pack Left', 'Power Pack Left'), ('Power Pack Right', 'Power Pack Right'), ('Impact Hours', 'Impact Hours'), ('Impact Left', 'Impact Left'), ('Impact Right', 'Impact Right'), ('Operating Hours', 'Operating Hours'), ('Calendar Years', 'Calendar Years')], null=True)),
                ('Eng_Tier', models.CharField(blank=True, choices=[('N/A', 'N/A'), ('Tier 2', 'Tier 2'), ('Tier 3', 'Tier 3'), ('Tier 4', 'Tier 4')], null=True)),
                ('Box_Type', models.CharField(blank=True, choices=[('Dump', 'Dump'), ('Ejector', 'Ejector')], null=True)),
                ('Additional_Information', models.TextField(blank=True)),
                ('Equipment_Image', models.ImageField(blank=True, null=True, upload_to='equipment_pics/')),
                ('Asset_Type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipment.assettype')),
                ('Equipment_Type', models.ForeignKey(db_column='Equipment_Type', on_delete=django.db.models.deletion.PROTECT, to='equipment.eq_type')),
                ('Garage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facilities.facility', to_field='Facility_Name')),
            ],
            options={
                'db_table': 'tarmor_equipment',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ComponentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Work_Order_Number', models.CharField(max_length=50)),
                ('Change_Date', models.DateField()),
                ('Change_Type', models.CharField(choices=[('Replaced New', 'Replaced New'), ('Replaced Reman', 'Replaced Reman'), ('Rebuilt', 'Rebuilt')], max_length=50)),
                ('Meter_Description', models.CharField(choices=[('', 'Select'), ('Engine Hours', 'Engine Hours'), ('Odometer', 'Odometer'), ('Power Pack Hours', 'Power Pack Hours'), ('Power Pack Left', 'Power Pack Left'), ('Power Pack Right', 'Power Pack Right'), ('Impact Hours', 'Impact Hours'), ('Impact Left', 'Impact Left'), ('Impact Right', 'Impact Right'), ('Operating Hours', 'Operating Hours')], max_length=50)),
                ('Meter_Reading', models.DecimalField(decimal_places=0, max_digits=12)),
                ('Old_Serial', models.CharField(max_length=50)),
                ('New_Serial', models.CharField(max_length=50)),
                ('New_Make', models.CharField(max_length=50)),
                ('New_Model', models.CharField(max_length=50)),
                ('New_PO', models.CharField(max_length=50)),
                ('New_Lifespan', models.CharField(max_length=50)),
                ('New_UoM', models.CharField(max_length=10)),
                ('New_Wty_Dur', models.CharField(max_length=50)),
                ('New_Wty_UoM', models.CharField(max_length=10)),
                ('New_Wty_Start', models.DateField(blank=True, null=True)),
                ('New_Wty_End', models.DateField(blank=True, null=True)),
                ('Additional_Information', models.TextField(blank=True)),
                ('Date_Recorded', models.DateTimeField(auto_now_add=True)),
                ('Component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='equipment.component')),
                ('Equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.equipment')),
            ],
            options={
                'db_table': 'tarmor_component_history',
                'ordering': ['-Change_Date'],
            },
        ),
        migrations.AddField(
            model_name='component',
            name='Equipment',
            field=models.ForeignKey(db_column='Equipment_Number', on_delete=django.db.models.deletion.CASCADE, related_name='components', to='equipment.equipment'),
        ),
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_type', models.CharField(choices=[('', 'Select'), ('Engine Hours', 'Engine Hours'), ('Odometer', 'Odometer'), ('Power Pack Hours', 'Power Pack Hours'), ('Power Pack Left', 'Power Pack Left'), ('Power Pack Right', 'Power Pack Right'), ('Impact Hours', 'Impact Hours'), ('Impact Left', 'Impact Left'), ('Impact Right', 'Impact Right'), ('Operating Hours', 'Operating Hours'), ('Calendar Years', 'Calendar Years')], max_length=50)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meters', to='equipment.equipment')),
            ],
            options={
                'db_table': 'tarmor_meter',
            },
        ),
        migrations.CreateModel(
            name='ShiftReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shift', models.CharField(choices=[('DS', 'Day Shift'), ('NS', 'Night Shift')], max_length=2)),
                ('mining_supervisor', models.CharField(max_length=100)),
                ('maint_supervisor', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hourly_data', models.JSONField(default=dict)),
                ('asset_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.assettype')),
                ('garage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_reports', to='facilities.facility')),
            ],
            options={
                'unique_together': {('date', 'shift')},
            },
        ),
        migrations.CreateModel(
            name='MachineShiftStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_down', models.FloatField(default=0.0)),
                ('total_worked', models.FloatField(default=0.0)),
                ('available', models.FloatField(default=12.0)),
                ('final_status', models.CharField(choices=[('Available', 'Available'), ('Down', 'Down')], max_length=10)),
                ('grid_data', models.TextField(help_text='Comma-separated D, W, P, or empty values')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.equipment')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='equipment.shiftreport')),
            ],
        ),
    ]
