# Generated by Django 6.0.4 on 2026-06-04 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assettype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
