# Generated by Django 6.0.4 on 2026-06-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_assettype_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eq_type',
            options={'managed': True, 'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='eq_type',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='eq_type',
            name='Prefix',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
