# Generated by Django 6.0.4 on 2026-06-04 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_alter_eq_type_options_eq_type_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='componenttype',
            options={'ordering': ['asset_type__name', 'name'], 'verbose_name_plural': 'Component Types'},
        ),
        migrations.AlterUniqueTogether(
            name='componenttype',
            unique_together={('name', 'asset_type')},
        ),
        migrations.AddField(
            model_name='componenttype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='componenttype',
            name='short_code',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
