# Generated by Django 6.0.4 on 2026-06-05 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_alter_componenttype_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='componenttype',
            options={'ordering': ['name'], 'verbose_name_plural': 'Component Types'},
        ),
    ]
