# Generated by Django 6.0.4 on 2026-06-05 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_alter_componenttype_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='componenttype',
            table='equipment_componenttype',
        ),
    ]
