# Generated by Django 6.0.2 on 2026-03-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_key', models.CharField(choices=[('', 'Select'), ('F', 'F'), ('M', 'M')], max_length=1)),
                ('system_name', models.CharField(max_length=50)),
                ('system_key', models.CharField(max_length=3)),
                ('combined_sys_key', models.CharField(max_length=4, unique=True)),
            ],
        ),
    ]
