# Generated by Django 6.0.2 on 2026-03-23 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('failures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_name', models.CharField(max_length=50)),
                ('component_key', models.CharField(max_length=3)),
                ('combined_comp_key', models.CharField(max_length=7, unique=True)),
                ('combined_sys_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='failures.System')),
            ],
        ),
    ]
