# Generated by Django 6.0.2 on 2026-03-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('failures', '0002_component'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='combined_comp_key',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='component_key',
            field=models.CharField(max_length=4),
        ),
    ]
