# Generated by Django 6.0.2 on 2026-03-23 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('failures', '0003_alter_component_combined_comp_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailureType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failure_mode', models.CharField(max_length=50)),
                ('failure_code', models.CharField(max_length=4)),
            ],
        ),
    ]
