# Generated by Django 6.0.2 on 2026-03-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('failures', '0004_failuretype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_name', models.CharField(max_length=50)),
                ('action_key', models.CharField(max_length=3)),
            ],
        ),
        migrations.AlterField(
            model_name='failuretype',
            name='failure_code',
            field=models.CharField(max_length=3),
        ),
    ]
