# Generated by Django 6.0.2 on 2026-03-31 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=20)),
                ('part_description', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(blank=True, max_length=255, null=True)),
                ('qty', models.IntegerField()),
                ('uom', models.CharField(max_length=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.CharField(choices=[('Stock', 'Stock'), ('Non-Stock', 'Non-Stock')], max_length=10)),
                ('controlled_product', models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], max_length=3)),
                ('alternatives', models.ManyToManyField(blank=True, to='inventory.inventoryitem')),
                ('supplier', models.ForeignKey(db_column='supplier_name', on_delete=django.db.models.deletion.PROTECT, to='suppliers.supplier')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('part_number', 'manufacturer'), name='unique_part_manufacturer')],
            },
        ),
    ]
