# Generated by Django 6.0.2 on 2026-04-01 13:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManageInv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin_location', models.CharField(max_length=50)),
                ('qty_onhand', models.IntegerField()),
                ('min_qty', models.IntegerField()),
                ('max_qty', models.IntegerField()),
                ('last_transaction_date', models.DateField(default=django.utils.timezone.now)),
                ('last_transaction_number', models.CharField(max_length=10)),
                ('part_description', models.ForeignKey(db_column='part_description', on_delete=django.db.models.deletion.PROTECT, related_name='manage_part_description', to='inventory.inventoryitem')),
                ('part_number', models.ForeignKey(db_column='part_number', on_delete=django.db.models.deletion.PROTECT, related_name='manage_part_number', to='inventory.inventoryitem')),
                ('uom', models.ForeignKey(db_column='uom', on_delete=django.db.models.deletion.PROTECT, related_name='manage_uom', to='inventory.inventoryitem')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_number', models.CharField(max_length=10)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('bill_location', models.CharField(choices=[('Work Order', 'Work Order'), ('General Acc', 'General Acc')], max_length=30)),
                ('wo_cc', models.CharField(max_length=10)),
                ('qty', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipped', models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], max_length=3)),
                ('additional_information', models.TextField(blank=True, null=True)),
                ('part_description', models.ForeignKey(db_column='part_description', on_delete=django.db.models.deletion.PROTECT, related_name='purchase_part_description', to='inventory.inventoryitem')),
                ('part_number', models.ForeignKey(db_column='part_number', on_delete=django.db.models.deletion.PROTECT, related_name='purchase_part_number', to='inventory.inventoryitem')),
                ('stock', models.ForeignKey(db_column='stock', on_delete=django.db.models.deletion.PROTECT, related_name='purchase_stock', to='inventory.inventoryitem')),
                ('supplier', models.ForeignKey(db_column='supplier_name', on_delete=django.db.models.deletion.PROTECT, related_name='purchase_supplier', to='suppliers.supplier')),
                ('unit_price', models.ForeignKey(db_column='unit_price', on_delete=django.db.models.deletion.PROTECT, related_name='purchase_unit_price', to='inventory.inventoryitem')),
                ('uom', models.ForeignKey(db_column='uom', on_delete=django.db.models.deletion.PROTECT, related_name='purchase_uom', to='inventory.inventoryitem')),
            ],
        ),
    ]
