# Generated by Django 6.0.2 on 2026-04-01 16:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_manageinv_purchaserequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='bin_location',
            field=models.CharField(default='A', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='last_transaction_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='last_transaction_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='max_qty',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='min_qty',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='qty_onhand',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ManageInv',
        ),
    ]
