# Generated by Django 6.0.2 on 2026-04-01 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventoryitem_bin_location_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PurchaseRequest',
        ),
    ]
