# Generated by Django 6.0.4 on 2026-05-29 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        ('work_orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityMaintenanceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qm_number', models.CharField(max_length=9, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('qm_type', models.CharField(choices=[('CALENDAR', 'Calendar'), ('METER', 'Meter')], max_length=10)),
                ('step_type', models.CharField(choices=[('SINGLE', 'Single Step'), ('MULTI', 'Multi-Step')], max_length=10)),
                ('work_order_lead_days', models.PositiveIntegerField(default=14)),
                ('single_interval_value', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('calendar_unit', models.CharField(blank=True, choices=[('DAY', 'Days'), ('WEEK', 'Weeks'), ('MONTH', 'Months'), ('YEAR', 'Years')], max_length=10, null=True)),
                ('est_work_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('single_interval_checklist', models.FileField(blank=True, null=True, upload_to='qm_checklists/')),
                ('single_interval_parts_list', models.FileField(blank=True, null=True, upload_to='qm_partslists/')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'planning_qualitymaintenancedocument',
                'ordering': ['qm_number'],
            },
        ),
        migrations.CreateModel(
            name='QualityMaintenanceDocumentStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.PositiveIntegerField()),
                ('interval_value', models.DecimalField(decimal_places=0, max_digits=12)),
                ('interval_unit', models.CharField(blank=True, choices=[('DAY', 'Days'), ('WEEK', 'Weeks'), ('MONTH', 'Months'), ('YEAR', 'Years')], max_length=10, null=True)),
                ('step_label', models.CharField(blank=True, max_length=100)),
                ('est_work_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('step_checklist', models.FileField(blank=True, null=True, upload_to='qm_checklists/')),
                ('step_parts_list', models.FileField(blank=True, null=True, upload_to='qm_partslists/')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='planning.qualitymaintenancedocument')),
            ],
            options={
                'db_table': 'planning_qualitymaintenancedocumentstep',
                'ordering': ['step_order'],
                'unique_together': {('document', 'step_order')},
            },
        ),
        migrations.CreateModel(
            name='QualityMaintenancePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('meter_start', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='planning.qualitymaintenancedocument')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_maintenance_plans', to='equipment.equipment')),
                ('meter_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_maintenance_plans', to='equipment.meter')),
            ],
            options={
                'db_table': 'planning_qualitymaintenanceplan',
                'ordering': ['document__qm_number', 'equipment'],
            },
        ),
        migrations.CreateModel(
            name='QualityMaintenanceInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('due_meter', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('FORECAST', 'Forecast'), ('DUE', 'Due'), ('TRIGGERED', 'Triggered'), ('COMPLETE', 'Complete')], default='FORECAST', max_length=20)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('completed_meter', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planning.qualitymaintenancedocumentstep')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qm_instances', to='work_orders.workorder')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='planning.qualitymaintenanceplan')),
            ],
            options={
                'db_table': 'planning_qualitymaintenanceinstance',
                'ordering': ['-created_at'],
            },
        ),
    ]
