# Generated by Django 6.0.4 on 2026-04-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moc', '0002_load_effval_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moc',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Deferred', 'Deferred'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], max_length=10),
        ),
    ]
