# Generated by Django 6.0.4 on 2026-04-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moc', '0003_alter_moc_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mocquestion',
            name='section',
            field=models.CharField(choices=[('safety_health', 'Safety & Health'), ('documentation', 'Documentation'), ('education', 'Education'), ('procurement', 'Procurement'), ('data_tech', 'Data & Technology'), ('test_imp', 'Test & Implementation'), ('social', 'Social')], max_length=30),
        ),
    ]
