# Generated by Django 6.0.4 on 2026-04-30 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moc', '0004_alter_mocquestion_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='safety',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='safety',
            name='leg_stnds',
        ),
        migrations.RemoveField(
            model_name='safety',
            name='pol_pros',
        ),
        migrations.RemoveField(
            model_name='safety',
            name='sds',
        ),
        migrations.AlterField(
            model_name='safety',
            name='moc',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='safety', to='moc.moc'),
        ),
    ]
