# Generated by Django 6.0.4 on 2026-04-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moc', '0006_alter_mocquestion_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safety',
            name='env_freq',
            field=models.CharField(blank=True, choices=[('0', '0'), ('2', '2'), ('4', '4'), ('6', '6'), ('8', '8'), ('10', '10')], max_length=4),
        ),
        migrations.AlterField(
            model_name='safety',
            name='fin_freq',
            field=models.CharField(blank=True, choices=[('0', '0'), ('2', '2'), ('4', '4'), ('6', '6'), ('8', '8'), ('10', '10')], max_length=4),
        ),
        migrations.AlterField(
            model_name='safety',
            name='sh_freq',
            field=models.CharField(blank=True, choices=[('0', '0'), ('2', '2'), ('4', '4'), ('6', '6'), ('8', '8'), ('10', '10')], max_length=4),
        ),
        migrations.AlterField(
            model_name='safety',
            name='soc_freq',
            field=models.CharField(blank=True, choices=[('0', '0'), ('2', '2'), ('4', '4'), ('6', '6'), ('8', '8'), ('10', '10')], max_length=4),
        ),
    ]
