# Generated by Django 6.0.4 on 2026-04-30 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moc', '0007_alter_safety_env_freq_alter_safety_fin_freq_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mocattachment',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='moccon',
            name='text',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mocpro',
            name='text',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
