# Generated by Django 6.0.4 on 2026-05-01 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moc', '0008_alter_mocattachment_description_alter_moccon_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moc',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Deferred', 'Deferred'), ('In Progress', 'In Progress'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], max_length=12),
        ),
    ]
