# Generated by Django 6.0.4 on 2026-05-06 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moc', '0009_alter_moc_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='moceffvalpoint',
            name='ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moceffvalpoint',
            name='effort',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='moceffvalpoint',
            name='value',
            field=models.FloatField(),
        ),
    ]
