# Generated by Django 6.0.4 on 2026-05-29 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        ('work_orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RimInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_tested', models.DateField()),
                ('rim_id', models.CharField(blank=True, max_length=255, null=True)),
                ('pass_fail', models.CharField(blank=True, choices=[('New', 'New'), ('Pass', 'Pass'), ('Fail', 'Fail')], max_length=4, null=True)),
                ('failure_reason', models.CharField(blank=True, choices=[('Bent', 'Bent'), ('Cracked', 'Cracked'), ('Corroded', 'Corroded'), ('Excessive Wear', 'Excessive Wear'), ('Centre Plate Damage', 'Centre Plate Damage'), ('Run Flat', 'Run Flat'), ('Lock Ring Groove Failure', 'Lock Ring Groove Failure'), ('Gutter Section Failure', 'Gutter Section Failure'), ('Other', 'Other')], max_length=50, null=True)),
                ('last_test_date', models.DateField(blank=True, null=True)),
                ('number_of_tests', models.IntegerField(blank=True, null=True)),
                ('next_test_date', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'ordering': ['-date_tested', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TireChangeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tire_id_off', models.CharField(blank=True, max_length=50, null=True)),
                ('tire_id_on', models.CharField(blank=True, max_length=50, null=True)),
                ('position', models.CharField(blank=True, choices=[('Front Left', 'Front Left'), ('Front Right', 'Front Right'), ('Centre Left', 'Centre Left'), ('Centre Right', 'Centre Right'), ('Centre Outside Left', 'Centre Outside Left'), ('Centre Outside Right', 'Centre Outside Right'), ('Centre Inside Left', 'Centre Inside Left'), ('Centre Inside Right', 'Centre Inside Right'), ('Rear Left', 'Rear Left'), ('Rear Right', 'Rear Right'), ('Rear Outside Left', 'Rear Outside Left'), ('Rear Outside Right', 'Rear Outside Right'), ('Rear Inside Left', 'Rear Inside Left'), ('Rear Inside Right', 'Rear Inside Right')], max_length=50, null=True)),
                ('tread_depth_off', models.IntegerField(blank=True, null=True)),
                ('tread_depth_on', models.IntegerField(blank=True, null=True)),
                ('rim_id_off', models.CharField(blank=True, max_length=50, null=True)),
                ('rim_id_on', models.CharField(blank=True, max_length=50, null=True)),
                ('tire_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('inflation_pressure', models.IntegerField(blank=True, null=True)),
                ('scrapped', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True)),
                ('recapped', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TireFailure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failure_mode', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TireInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(blank=True, max_length=50, null=True)),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('tire_size', models.CharField(blank=True, max_length=50, null=True)),
                ('tire_face', models.CharField(blank=True, choices=[('Smooth', 'Smooth'), ('Treaded', 'Treaded')], max_length=50, null=True)),
                ('tread_depth_new', models.IntegerField(blank=True, null=True)),
                ('inflation_pressure', models.IntegerField(blank=True, null=True)),
                ('tire_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TireInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meter_reading', models.IntegerField(blank=True, null=True)),
                ('comments', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TireInspectionReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tire_id', models.CharField(blank=True, max_length=50, null=True)),
                ('position', models.CharField(blank=True, choices=[('Front Left', 'Front Left'), ('Front Right', 'Front Right'), ('Centre Left', 'Centre Left'), ('Centre Right', 'Centre Right'), ('Centre Outside Left', 'Centre Outside Left'), ('Centre Outside Right', 'Centre Outside Right'), ('Centre Inside Left', 'Centre Inside Left'), ('Centre Inside Right', 'Centre Inside Right'), ('Rear Left', 'Rear Left'), ('Rear Right', 'Rear Right'), ('Rear Outside Left', 'Rear Outside Left'), ('Rear Outside Right', 'Rear Outside Right'), ('Rear Inside Left', 'Rear Inside Left'), ('Rear Inside Right', 'Rear Inside Right')], max_length=50, null=True)),
                ('tread_depth', models.IntegerField(blank=True, null=True)),
                ('inflation_pressure', models.IntegerField(blank=True, null=True)),
                ('tire_diameter', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ValveSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meter_reading', models.IntegerField(blank=True, null=True)),
                ('comments', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ValveSetReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cylinder_number', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], max_length=2, null=True)),
                ('int_exh', models.CharField(blank=True, choices=[('Int', 'Intake'), ('Exh', 'Exhaust')], max_length=3, null=True)),
                ('valve_number', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=2, null=True)),
                ('valve_setting', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
            ],
            options={
                'ordering': ['cylinder_number', 'int_exh', 'valve_number'],
            },
        ),
        migrations.CreateModel(
            name='BoxLiner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meter_reading', models.IntegerField(blank=True, null=True)),
                ('comments', models.CharField(blank=True, max_length=255, null=True)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='box_liners', to='equipment.equipment')),
                ('meter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='box_liners', to='equipment.meter')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='box_liners', to='work_orders.workorder')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BucketLip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meter_reading', models.IntegerField(blank=True, null=True)),
                ('comments', models.CharField(blank=True, max_length=255, null=True)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bucket_lips', to='equipment.equipment')),
                ('meter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bucket_lips', to='equipment.meter')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bucket_lips', to='work_orders.workorder')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CycleTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meter_reading', models.IntegerField(blank=True, null=True)),
                ('comments', models.CharField(blank=True, max_length=255, null=True)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cycle_times', to='equipment.equipment')),
                ('meter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cycle_times', to='equipment.meter')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cycle_times', to='work_orders.workorder')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CycleTimeMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(blank=True, choices=[('Steering', 'Steering'), ('Ejector', 'Ejector'), ('Lift', 'Lift'), ('Tilt', 'Tilt'), ('Boom', 'Boom'), ('Stick', 'Stick'), ('Turret', 'Turret'), ('Telescopic', 'Telescopic'), ('House', 'House'), ('Scissor', 'Scissor'), ('Drill Feed', 'Drill Feed'), ('Bolt Feed', 'Bolt Feed'), ('Boom Feed', 'Boom Feed')], max_length=50, null=True)),
                ('position', models.CharField(blank=True, choices=[('Left', 'Left'), ('Right', 'Right'), ('Up', 'Up'), ('Down', 'Down'), ('Tilt', 'Tilt'), ('Rollback', 'Rollback'), ('Extend', 'Extend'), ('Retract', 'Retract'), ('Swing/Rotate CW', 'Swing/Rotate CW'), ('Swing/Rotate CCW', 'Swing/Rotate CCW'), ('In', 'Int'), ('Out', 'Out')], max_length=50, null=True)),
                ('time', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('cycle_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_time_measurements', to='condition_monitoring.cycletime')),
            ],
            options={
                'ordering': ['system', 'time'],
            },
        ),
        migrations.CreateModel(
            name='CylinderTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meter_reading', models.IntegerField(blank=True, null=True)),
                ('comments', models.CharField(blank=True, max_length=255, null=True)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cylinder_temps', to='equipment.equipment')),
                ('meter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cylinder_temps', to='equipment.meter')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cylinder_temps', to='work_orders.workorder')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CylinderTempReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cylinder_number', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('Turbo', 'Turbo')], max_length=6, null=True)),
                ('temp_reading', models.CharField(blank=True, max_length=4, null=True)),
                ('uom', models.CharField(blank=True, choices=[('degrees C', 'degrees C'), ('degrees F', 'degrees F')], max_length=10, null=True)),
                ('cylinder_temp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cyl_temp_readings', to='condition_monitoring.cylindertemp')),
            ],
            options={
                'ordering': ['cylinder_number', 'temp_reading', 'uom'],
            },
        ),
        migrations.CreateModel(
            name='FilterRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meter_reading', models.IntegerField(blank=True, null=True)),
                ('compartment', models.CharField(blank=True, choices=[('Engine', 'Engine'), ('Transmission', 'Transmission'), ('Trans Mag Strain', 'Trans Mag Strain'), ('Upbox', 'Upbox'), ('Dropbox', 'Dropbox'), ('Hydraulic', 'Hydraulic'), ('Front Diff', 'Front Diff'), ('Centre Diff', 'Centre Diff'), ('Rear Diff', 'Rear Diff')], null=True)),
                ('filter_rating', models.IntegerField(blank=True, choices=[(1, '1 - Good'), (2, '2 - Fair'), (3, '3 - Poor'), (4, '4 - Critical Failure')], null=True)),
                ('comments', models.CharField(blank=True, max_length=255, null=True)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filter_rating_eq', to='equipment.equipment')),
                ('meter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filter_rating_mtr', to='equipment.meter')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filter_rating_wo', to='work_orders.workorder')),
            ],
        ),
        migrations.CreateModel(
            name='LinerMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, choices=[('Pos 1', 'Pos 1'), ('Pos 2', 'Pos 2'), ('Pos 3', 'Pos 3'), ('Pos 4', 'Pos 4'), ('Pos 5', 'Pos 5'), ('Pos 6', 'Pos 6'), ('Pos 7', 'Pos 7'), ('Pos 8', 'Pos 8'), ('Pos 9', 'Pos 9'), ('Pos 10', 'Pos 10'), ('Pos 11', 'Pos 11'), ('Pos 12', 'Pos 12'), ('Pos 13', 'Pos 13')], max_length=6, null=True)),
                ('pos_reading', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('box_liner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liner_measurements', to='condition_monitoring.boxliner')),
            ],
            options={
                'ordering': ['position', 'pos_reading'],
            },
        ),
        migrations.CreateModel(
            name='LipMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_side', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('right_side', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('centre', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('bucket_lip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lip_measurements', to='condition_monitoring.bucketlip')),
            ],
            options={
                'ordering': ['left_side', 'right_side', 'centre'],
            },
        ),
        migrations.CreateModel(
            name='MagPlug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meter_reading', models.IntegerField(blank=True, null=True)),
                ('compartment', models.CharField(blank=True, choices=[('Engine', 'Engine'), ('Transmission', 'Transmission'), ('Trans Mag Strain', 'Trans Mag Strain'), ('Upbox', 'Upbox'), ('Dropbox', 'Dropbox'), ('Hydraulic', 'Hydraulic'), ('Front Diff', 'Front Diff'), ('Centre Diff', 'Centre Diff'), ('Rear Diff', 'Rear Diff')], null=True)),
                ('plug_rating', models.IntegerField(blank=True, choices=[(1, '1 - Excellent'), (2, '2 - Good'), (3, '3 - Fair'), (4, '4 - Poor'), (5, '5 - Critical Failure')], null=True)),
                ('comments', models.CharField(blank=True, max_length=255, null=True)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mag_plug_eq', to='equipment.equipment')),
                ('meter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mag_plug_mtr', to='equipment.meter')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mag_plug_wo', to='work_orders.workorder')),
            ],
        ),
        migrations.CreateModel(
            name='ShortTermCM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('equipment_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('troubleshoot_desc', models.TextField(blank=True, null=True)),
                ('repair_desc', models.TextField(blank=True, null=True)),
                ('problem', models.CharField(max_length=255)),
                ('corrective_action', models.CharField(max_length=255)),
                ('due_date', models.DateField()),
                ('progress', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Complete', 'Complete'), ('Canceled', 'Canceled')], max_length=15)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('complete', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=15)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shortterm_equipment', to='equipment.equipment')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shortterm_wo', to='work_orders.workorder')),
            ],
        ),
        migrations.CreateModel(
            name='TireChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meter_reading', models.IntegerField(blank=True, null=True)),
                ('comments', models.CharField(blank=True, max_length=255, null=True)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tire_changes', to='equipment.equipment')),
                ('meter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tire_changes', to='equipment.meter')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tire_changes', to='work_orders.workorder')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
