# Generated by Django 6.0.4 on 2026-05-29 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('condition_monitoring', '0001_initial'),
        ('equipment', '0001_initial'),
        ('purchasing', '0001_initial'),
        ('work_orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tirechangeinfo',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tire_changes', to='purchasing.purchase'),
        ),
        migrations.AddField(
            model_name='tirechangeinfo',
            name='tire_change',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tire_change_info', to='condition_monitoring.tirechange'),
        ),
        migrations.AddField(
            model_name='tirechangeinfo',
            name='reason_for_failure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tire_changes_failure', to='condition_monitoring.tirefailure'),
        ),
        migrations.AddField(
            model_name='tirechangeinfo',
            name='scrap_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tire_changes_scrap', to='condition_monitoring.tirefailure'),
        ),
        migrations.AddField(
            model_name='tireinformation',
            name='asset_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tire_info_asset', to='equipment.assettype'),
        ),
        migrations.AddField(
            model_name='tireinformation',
            name='equipment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tire_info_eq', to='equipment.eq_type'),
        ),
        migrations.AddField(
            model_name='tireinspection',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tire_inspections', to='equipment.equipment'),
        ),
        migrations.AddField(
            model_name='tireinspection',
            name='meter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tire_inspections', to='equipment.meter'),
        ),
        migrations.AddField(
            model_name='tireinspection',
            name='work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tire_inspections', to='work_orders.workorder'),
        ),
        migrations.AddField(
            model_name='tireinspectionreading',
            name='tire_inspection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tire_inspection_readings', to='condition_monitoring.tireinspection'),
        ),
        migrations.AddField(
            model_name='valveset',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valve_sets', to='equipment.equipment'),
        ),
        migrations.AddField(
            model_name='valveset',
            name='meter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valve_sets', to='equipment.meter'),
        ),
        migrations.AddField(
            model_name='valveset',
            name='work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valve_sets', to='work_orders.workorder'),
        ),
        migrations.AddField(
            model_name='valvesetreading',
            name='valve_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='condition_monitoring.valveset'),
        ),
    ]
