# Generated by Django 6.0.4 on 2026-05-24 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0019_alter_component_wty_uom'),
    ]

    operations = [
        migrations.CreateModel(
            name='RebuildPlanRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervention_type', models.CharField(choices=[('Rebuild', 'Rebuild'), ('Replace', 'Replacement')], max_length=10)),
                ('intervention_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('calculated_year', models.IntegerField()),
                ('modified_year', models.IntegerField(blank=True, null=True)),
                ('project_number', models.CharField(blank=True, max_length=50, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_complete', models.BooleanField(default=False)),
                ('iteration_cycle', models.IntegerField(default=1)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rebuild_plans', to='equipment.equipment')),
            ],
            options={
                'db_table': 'reliability_rebuildplanrow',
                'unique_together': {('equipment', 'calculated_year', 'intervention_type', 'iteration_cycle')},
            },
        ),
    ]
