# Generated by Django 6.0.2 on 2026-04-18 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WorkWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveSmallIntegerField(unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locked', models.BooleanField(default=False)),
                ('last_saved', models.DateTimeField(auto_now=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('responsible_garage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scheduling.garage')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.workweek')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_order_no', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('planned_start', models.DateField(blank=True, null=True)),
                ('estimated_hours', models.DecimalField(decimal_places=2, max_digits=6)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('job_status', models.CharField(choices=[('Waiting to Schedule', 'Waiting to Schedule'), ('Reschedule', 'Reschedule'), ('Execution', 'Execution')], default='Waiting to Schedule', max_length=30)),
                ('responsible_garage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scheduling.garage')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_start_snapshot', models.DateField()),
                ('estimated_hours_snapshot', models.DecimalField(decimal_places=2, max_digits=6)),
                ('job_status_snapshot', models.CharField(max_length=30)),
                ('completion_date_snapshot', models.DateField(blank=True, null=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.schedule')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scheduling.workorder')),
            ],
        ),
    ]
