# Generated by Django 6.0.4 on 2026-04-23 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_rename_street_address_1_facility_street_address_and_more'),
        ('personnel', '0012_crew_shiftpattern_remove_employee_location_and_more'),
        ('scheduling', '0001_initial'),
        ('work_orders', '0008_workorder_plan_shift'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Monday', max_length=10)),
                ('week1_start_date', models.DateField(verbose_name='Start Date for Week 1')),
                ('active', models.BooleanField(default=True, help_text='Only one active setup should exist at a time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='responsible_garage',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='responsible_garage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facilities.facility', verbose_name='Garage'),
        ),
        migrations.AlterField(
            model_name='schedulesnapshot',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='work_orders.workorder'),
        ),
        migrations.AlterModelOptions(
            name='workweek',
            options={'ordering': ['week_number']},
        ),
        migrations.RenameField(
            model_name='schedulesnapshot',
            old_name='completion_date_snapshot',
            new_name='date_closed_snapshot',
        ),
        migrations.RenameField(
            model_name='schedulesnapshot',
            old_name='planned_start_snapshot',
            new_name='plan_start_snapshot',
        ),
        migrations.AlterField(
            model_name='schedulesnapshot',
            name='job_status_snapshot',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='schedulesnapshot',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='scheduling.schedule'),
        ),
        migrations.AlterField(
            model_name='workweek',
            name='week_number',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.CreateModel(
            name='DailyCrewCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('available_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('assigned_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personnel.crew')),
                ('workweek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.workweek')),
            ],
        ),
        migrations.AddField(
            model_name='workweek',
            name='setup',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='scheduling.weeksetup'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='workweek',
            unique_together={('setup', 'week_number')},
        ),
        migrations.DeleteModel(
            name='Garage',
        ),
        migrations.DeleteModel(
            name='WorkOrder',
        ),
    ]
