# Generated by Django 6.0.4 on 2026-05-15 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0004_facility_shop_rate'),
        ('scheduling', '0002_weeksetup_remove_workorder_responsible_garage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeOffLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ds_off', models.IntegerField(default=0)),
                ('ns_off', models.IntegerField(default=0)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_off_logs', to='facilities.facility')),
            ],
            options={
                'db_table': 'tarmor_time_off_log',
                'unique_together': {('facility', 'date')},
            },
        ),
    ]
