# Generated by Django 6.0.2 on 2026-03-27 02:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personnel', '0011_alter_employee_prov_state'),
        ('work_orders', '0004_workorder_hot_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('finish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_time', models.FloatField(blank=True, null=True)),
                ('time_type', models.CharField(choices=[('Prep', 'Prep'), ('Travel', 'Travel'), ('Troubleshoot', 'Troubleshoot')], max_length=15)),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timesheets', to='personnel.employee')),
                ('work_order', models.ForeignKey(db_column='work_order', on_delete=django.db.models.deletion.PROTECT, to='work_orders.workorder')),
            ],
        ),
    ]
