# Generated by Django 6.0.2 on 2026-03-27 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='time_type',
            field=models.CharField(choices=[('Prep', 'Prep'), ('Travel', 'Travel'), ('Troubleshoot', 'Troubleshoot'), ('Repair', 'Repair')], max_length=15),
        ),
    ]
