# Generated by Django 6.0.4 on 2026-05-06 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_number', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('moc_number', models.CharField(blank=True, max_length=100)),
                ('execution_time', models.IntegerField(default=1)),
                ('uom', models.CharField(default='Years', max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Deferred', 'Deferred'), ('In-Progress', 'In-Progress'), ('Complete', 'Complete'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('spend', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('remaining', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('scope', models.TextField(blank=True)),
                ('justification', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='project_attachments/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('time_to_implement', models.IntegerField()),
                ('uom', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDelay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delay_type', models.CharField(max_length=100)),
                ('cause', models.TextField()),
                ('time_requirement', models.IntegerField()),
                ('uom', models.CharField(max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delays', to='projects.project')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projectstep')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=50, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wo_number', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='projects.project')),
            ],
        ),
    ]
