# Generated by Django 6.0.4 on 2026-05-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_budget_alter_project_execution_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdelay',
            name='cause',
            field=models.CharField(max_length=100),
        ),
    ]
