# Generated by Django 6.0.4 on 2026-05-08 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projectbudget'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('step_note', models.CharField(blank=True, max_length=255)),
                ('action', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('progress', models.CharField(blank=True, max_length=100)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('complete', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='projects.project')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.projectstep')),
            ],
        ),
    ]
