# Generated by Django 6.0.4 on 2026-05-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_projectnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectnote',
            name='progress',
            field=models.TextField(blank=True),
        ),
    ]
