# Generated by Django 6.0.4 on 2026-05-08 18:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_projectnote_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectnote',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
