# Generated by Django 6.0.4 on 2026-05-08 18:52

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_projectnote_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('failure', models.CharField(blank=True, max_length=255)),
                ('action', models.TextField(blank=True)),
                ('lesson', models.CharField(blank=True, max_length=255)),
                ('progress', models.TextField(blank=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('complete', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='projects.project')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.projectstep')),
            ],
        ),
    ]
