# Generated by Django 6.0.4 on 2026-05-08 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_projectlesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFinancial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('jan_p', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('feb_p', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mar_p', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('apr_p', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('may_p', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('jun_p', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('jul_p', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('aug_p', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sep_p', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('oct_p', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('nov_p', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('dec_p', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financials', to='projects.project')),
            ],
        ),
    ]
