# Generated by Django 6.0.4 on 2026-05-09 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_projecttasks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projecttasks',
            old_name='taks',
            new_name='tasks',
        ),
    ]
