# Generated by Django 6.0.4 on 2026-05-10 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_rename_taks_projecttasks_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfinancial',
            name='cash_carryover',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='projectfinancial',
            name='cost_carryover',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
