# Generated by Django 6.0.4 on 2026-05-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_projectfinancial_cash_carryover_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='assigned_to',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='start_year',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
