# Generated by Django 6.0.4 on 2026-05-11 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_project_assigned_to_project_start_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
        ),
    ]
