# Generated by Django 6.0.4 on 2026-05-29 15:58

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('projects', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_type', models.CharField(choices=[('P', 'Purchase Order'), ('R', 'Purchase Requisition'), ('S', 'Service Order')], max_length=1)),
                ('purchase_number', models.CharField(blank=True, max_length=9, unique=True)),
                ('barcode_image', models.ImageField(blank=True, editable=False, upload_to='barcodes/')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('bill_location', models.CharField(choices=[('Work Order', 'Work Order'), ('Cost Centre', 'Cost Centre')], max_length=20)),
                ('wo_cc', models.CharField(max_length=50)),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Received', 'Received'), ('Cancelled', 'Cancelled'), ('Returned', 'Returned'), ('Paid', 'Paid')], default='Pending', max_length=10)),
                ('additional_information', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='projects.project')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number_input', models.CharField(max_length=100)),
                ('manual_part_number', models.CharField(blank=True, max_length=100)),
                ('manufacturer', models.CharField(blank=True, max_length=255)),
                ('part_description', models.CharField(blank=True, max_length=255)),
                ('uom', models.CharField(blank=True, max_length=30)),
                ('qty', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12)),
                ('row_status', models.CharField(choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Received', 'Received'), ('Cancelled', 'Cancelled'), ('Returned', 'Returned'), ('Paid', 'Paid')], default='Pending', max_length=10)),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventoryitem')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchasing.purchase')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.supplier')),
            ],
        ),
    ]
