# Generated by Django 6.0.2 on 2026-03-16 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CostCentre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cost_Centre', models.CharField(max_length=10, unique=True)),
                ('Cost_Centre_Description', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Cost Centre',
                'verbose_name_plural': 'Cost Centres',
                'ordering': ['Cost_Centre'],
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Facility_Code', models.CharField(help_text='This is the location code used later for shift IDs, e.g. 1800.', max_length=10, unique=True)),
                ('Facility_Name', models.CharField(max_length=60, unique=True)),
                ('Street_Address_1', models.CharField(blank=True, max_length=100)),
                ('Street_Address_2', models.CharField(blank=True, max_length=100)),
                ('City', models.CharField(blank=True, max_length=50)),
                ('Province_State', models.CharField(blank=True, max_length=25)),
                ('Country', models.CharField(blank=True, max_length=25)),
                ('Postal_Zip_Code', models.CharField(blank=True, max_length=12)),
                ('Contact_Name', models.CharField(blank=True, max_length=60)),
                ('Contact_Phone_Number', models.CharField(blank=True, max_length=25)),
                ('Email_Address', models.EmailField(blank=True, max_length=254)),
                ('Additional_Information', models.TextField(blank=True)),
                ('Cost_Centre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facilities.costcentre')),
            ],
            options={
                'verbose_name': 'Facility',
                'verbose_name_plural': 'Facilities',
                'ordering': ['Facility_Name'],
            },
        ),
    ]
