# Generated by Django 6.0.2 on 2026-03-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='costcentre',
            name='Status',
            field=models.CharField(choices=[('', 'Select'), ('Active', 'Active'), ('Inactive', 'Inactive')], default='Active'),
            preserve_default=False,
        ),
    ]
