# Generated by Django 6.0.2 on 2026-03-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_costcentre_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facility',
            old_name='Street_Address_1',
            new_name='Street_Address',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='Street_Address_2',
        ),
        migrations.AddField(
            model_name='facility',
            name='Status',
            field=models.CharField(choices=[('', 'Select'), ('Active', 'Active'), ('Inactive', 'Inactive')], default='Active'),
            preserve_default=False,
        ),
    ]
