# Generated by Django 6.0.4 on 2026-04-24 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_rename_street_address_1_facility_street_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='Shop_Rate',
            field=models.DecimalField(decimal_places=2, default=150.0, max_digits=6),
            preserve_default=False,
        ),
    ]
