# Generated by Django 6.0.4 on 2026-05-15 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0004_facility_shop_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costcentre',
            name='Cost_Centre',
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
