# Generated by Django 6.0.2 on 2026-04-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FailureFrequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_number', models.CharField(max_length=50)),
                ('equipment_description', models.CharField(max_length=255)),
                ('asset_type', models.CharField(max_length=100)),
                ('equipment_type', models.CharField(max_length=100)),
                ('equipment_hours', models.FloatField(help_text='Accumulated hours in range')),
                ('failure_count', models.IntegerField()),
                ('frequency', models.FloatField(help_text='Failures per hour')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
    ]
