# Generated by Django 6.0.2 on 2026-04-12 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MTBF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_number', models.CharField(max_length=50)),
                ('equipment_description', models.CharField(max_length=255)),
                ('asset_type', models.CharField(max_length=100)),
                ('equipment_type', models.CharField(max_length=100)),
                ('equipment_hours', models.FloatField(help_text='Accumulated hours in range')),
                ('failure_count', models.IntegerField()),
                ('mtbf', models.FloatField(help_text='Mean Time Between Failures')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
    ]
