# Generated by Django 6.0.4 on 2026-05-29 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(blank=True, null=True)),
                ('Meter_Replaced', models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=10)),
                ('Meter_Reading', models.IntegerField(blank=True, null=True)),
                ('Reading_Difference', models.IntegerField(blank=True, null=True)),
                ('Total_Meter_Value', models.IntegerField(blank=True, null=True)),
                ('Equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='equipment.equipment')),
                ('Meter_Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='equipment.meter')),
            ],
            options={
                'db_table': 'tarmor_meterreading',
                'constraints': [models.UniqueConstraint(fields=('Date', 'Equipment', 'Meter_Type'), name='unique_daily_reading')],
            },
        ),
    ]
