# Generated by Django 6.0.2 on 2026-03-13 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0009_alter_equipment_end_of_life_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(blank=True, null=True)),
                ('Meter_Replaced', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Active', max_length=10)),
                ('Meter_Reading', models.IntegerField(blank=True, null=True)),
                ('Reading_Difference', models.IntegerField(blank=True, null=True)),
                ('Total_Meter_Vale', models.IntegerField(blank=True, null=True)),
                ('Equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='equipment.equipment')),
                ('Meter_Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='equipment.meter')),
            ],
        ),
    ]
