# Generated by Django 6.0.2 on 2026-03-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterreading',
            name='Meter_Replaced',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='Active', max_length=10),
        ),
    ]
