# Generated by Django 6.0.2 on 2026-03-14 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0009_alter_equipment_end_of_life_and_more'),
        ('meters', '0002_alter_meterreading_meter_replaced'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='meterreading',
            constraint=models.UniqueConstraint(fields=('Date', 'Equipment', 'Meter_Type'), name='unique_daily_reading'),
        ),
        migrations.AlterModelTable(
            name='meterreading',
            table='tarmor_meterreading',
        ),
    ]
