# Generated by Django 6.0.2 on 2026-03-15 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0003_meterreading_unique_daily_reading_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meterreading',
            old_name='Total_Meter_Vale',
            new_name='Total_Meter_Value',
        ),
    ]
