# Generated by Django 6.0.2 on 2026-04-09 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0004_rename_total_meter_vale_meterreading_total_meter_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterreading',
            name='Meter_Replaced',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=10),
        ),
    ]
