# Generated by Django 6.0.2 on 2026-03-25 02:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0009_alter_equipment_end_of_life_and_more'),
        ('failures', '0005_action_alter_failuretype_failure_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_choice', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type', models.CharField(max_length=20)),
                ('work_description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_order', models.CharField(editable=False, max_length=9, unique=True)),
                ('barcode_image', models.ImageField(blank=True, upload_to='barcodes/')),
                ('priority', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default='3', max_length=1)),
                ('machine_oos', models.CharField(blank=True, choices=[('No', 'No'), ('Yes', 'Yes')], max_length=3, null=True)),
                ('hours', models.IntegerField(blank=True, null=True)),
                ('meter', models.CharField(blank=True, choices=[('', 'Select'), ('Engine Hours', 'Engine Hours'), ('Odometer', 'Odometer'), ('Power Pack Hours', 'Power Pack Hours'), ('Power Pack Left', 'Power Pack Left'), ('Power Pack Right', 'Power Pack Right'), ('Impact Hours', 'Impact Hours'), ('Impact Left', 'Impact Left'), ('Impact Right', 'Impact Right'), ('Operating Hours', 'Operating Hours')], max_length=30, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_closed', models.DateTimeField(blank=True, null=True)),
                ('troubleshoot_description', models.CharField(max_length=100)),
                ('ts_extended_description', models.TextField(blank=True, null=True)),
                ('equipment_location', models.CharField(blank=True, max_length=100, null=True)),
                ('ts_service_report', models.TextField(blank=True, null=True)),
                ('plan_start_date', models.DateTimeField(blank=True, null=True)),
                ('safety_instructions', models.TextField(blank=True, null=True)),
                ('spec_requirements', models.TextField(blank=True, null=True)),
                ('legislative', models.CharField(blank=True, choices=[('No', 'No'), ('Yes', 'Yes')], max_length=3, null=True)),
                ('license_req', models.CharField(blank=True, choices=[('No', 'No'), ('Yes', 'Yes')], max_length=3, null=True)),
                ('tools_req', models.CharField(blank=True, choices=[('No', 'No'), ('Yes', 'Yes')], max_length=3, null=True)),
                ('conf_space', models.CharField(blank=True, choices=[('No', 'No'), ('Yes', 'Yes')], max_length=3, null=True)),
                ('jha', models.CharField(blank=True, choices=[('No', 'No'), ('Yes', 'Yes')], max_length=3, null=True)),
                ('parts_wty', models.CharField(blank=True, choices=[('No', 'No'), ('Yes', 'Yes')], max_length=3, null=True)),
                ('work_wty', models.CharField(blank=True, choices=[('No', 'No'), ('Yes', 'Yes')], max_length=3, null=True)),
                ('repair_description', models.CharField(blank=True, max_length=100, null=True)),
                ('repair_extended_description', models.TextField(blank=True, null=True)),
                ('job_instructions', models.TextField(blank=True, null=True)),
                ('repair_service_report', models.TextField(blank=True, null=True)),
                ('equipment', models.ForeignKey(db_column='Equipment_Number', on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='equipment.equipment')),
                ('fc_action', models.ForeignKey(blank=True, db_column='action_name', null=True, on_delete=django.db.models.deletion.PROTECT, to='failures.action')),
                ('fc_component', models.ForeignKey(blank=True, db_column='component_name', null=True, on_delete=django.db.models.deletion.PROTECT, to='failures.component')),
                ('fc_failure_mode', models.ForeignKey(blank=True, db_column='failure_mode', null=True, on_delete=django.db.models.deletion.PROTECT, to='failures.failuretype')),
                ('fc_system', models.ForeignKey(blank=True, db_column='system_name', null=True, on_delete=django.db.models.deletion.PROTECT, to='failures.system')),
                ('job_status', models.ForeignKey(db_column='status_choice', on_delete=django.db.models.deletion.PROTECT, to='work_orders.statuschoices')),
                ('work_type', models.ForeignKey(db_column='work_type', on_delete=django.db.models.deletion.PROTECT, to='work_orders.worktype')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
