# Generated by Django 6.0.2 on 2026-03-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='job_status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='work_type',
            field=models.CharField(max_length=20),
        ),
    ]
