# Generated by Django 6.0.2 on 2026-03-25 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0002_alter_workorder_job_status_alter_workorder_work_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='job_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='work_orders.statuschoices'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='work_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='work_orders.worktype'),
        ),
    ]
