# Generated by Django 6.0.2 on 2026-03-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0003_alter_workorder_job_status_alter_workorder_work_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='hot_work',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('Yes', 'Yes')], max_length=3, null=True),
        ),
    ]
