# Generated by Django 6.0.2 on 2026-04-16 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0004_workorder_hot_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='attached_checklist',
            field=models.FileField(blank=True, null=True, upload_to='wo_attachments/'),
        ),
    ]
