# Generated by Django 6.0.2 on 2026-04-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0005_workorder_attached_checklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='est_work_hours',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
        ),
    ]
