# Generated by Django 6.0.2 on 2026-04-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0006_workorder_est_work_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='troubleshoot_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
