# Generated by Django 6.0.4 on 2026-04-22 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0007_alter_workorder_troubleshoot_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='plan_shift',
            field=models.CharField(choices=[('DS', 'Day Shift'), ('NS', 'Night Shift')], default='DS', max_length=2),
        ),
    ]
