# Generated by Django 6.0.4 on 2026-04-23 21:12

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('failures', '0005_action_alter_failuretype_failure_code'),
        ('work_orders', '0008_workorder_plan_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='fc_component',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='fc_system', chained_model_field='system_key_key', default=1, on_delete=django.db.models.deletion.CASCADE, to='failures.component'),
            preserve_default=False,
        ),
    ]
