# Generated by Django 6.0.4 on 2026-04-28 10:06

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('failures', '0005_action_alter_failuretype_failure_code'),
        ('work_orders', '0010_alter_workorder_fc_component'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='fc_component',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='fc_system', chained_model_field='combined_system_key', null=True, on_delete=django.db.models.deletion.CASCADE, to='failures.component'),
        ),
    ]
