# Generated by Django 6.0.4 on 2026-05-06 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0013_workorderattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='attached_parts_list',
            field=models.FileField(blank=True, null=True, upload_to='wo_attachments/'),
        ),
    ]
