# Generated by Django 6.0.2 on 2026-04-07 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0009_alter_equipment_end_of_life_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QMNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_suffix', models.CharField(max_length=2, unique=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='QualityMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qm_number', models.CharField(max_length=9, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('qm_type', models.CharField(choices=[('CALENDAR', 'Calendar'), ('METER', 'Meter')], max_length=10)),
                ('step_type', models.CharField(choices=[('SINGLE', 'Single Step'), ('MULTI', 'Multi-Step')], max_length=10)),
                ('start_date', models.DateField()),
                ('meter_start', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('daily_usage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('single_interval_days', models.PositiveIntegerField(blank=True, null=True)),
                ('single_interval_meter', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('work_order_lead_days', models.PositiveIntegerField(default=14)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_maintenances', to='equipment.equipment')),
            ],
            options={
                'ordering': ['qm_number'],
            },
        ),
        migrations.CreateModel(
            name='QualityMaintenanceStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.PositiveIntegerField()),
                ('interval_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('step_label', models.CharField(blank=True, max_length=100)),
                ('qm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='planning.qualitymaintenance')),
            ],
            options={
                'ordering': ['step_order'],
                'unique_together': {('qm', 'step_order')},
            },
        ),
        migrations.CreateModel(
            name='QualityMaintenanceInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('due_meter', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('work_order_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('FORECAST', 'Forecast'), ('DUE', 'Due'), ('TRIGGERED', 'Triggered'), ('COMPLETE', 'Complete')], default='FORECAST', max_length=20)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('completed_meter', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('qm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='planning.qualitymaintenance')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planning.qualitymaintenancestep')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
