# Generated by Django 6.0.4 on 2026-05-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualitymaintenancedocument',
            name='single_interval_parts_list',
            field=models.FileField(blank=True, null=True, upload_to='qm_partslists/'),
        ),
        migrations.AddField(
            model_name='qualitymaintenancedocumentstep',
            name='step_parts_list',
            field=models.FileField(blank=True, null=True, upload_to='qm_partslists/'),
        ),
    ]
