# Generated by Django 6.0.2 on 2026-04-09 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0009_alter_equipment_end_of_life_and_more'),
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qualitymaintenance',
            old_name='single_interval_meter',
            new_name='single_interval_value',
        ),
        migrations.RemoveField(
            model_name='qualitymaintenance',
            name='daily_usage',
        ),
        migrations.RemoveField(
            model_name='qualitymaintenance',
            name='single_interval_days',
        ),
        migrations.AddField(
            model_name='qualitymaintenance',
            name='calendar_unit',
            field=models.CharField(blank=True, choices=[('DAY', 'Days'), ('WEEK', 'Weeks'), ('MONTH', 'Months'), ('YEAR', 'Years')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='qualitymaintenance',
            name='meter_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_maintenances', to='equipment.meter'),
        ),
        migrations.AddField(
            model_name='qualitymaintenancestep',
            name='interval_unit',
            field=models.CharField(blank=True, choices=[('DAY', 'Days'), ('WEEK', 'Weeks'), ('MONTH', 'Months'), ('YEAR', 'Years')], max_length=10, null=True),
        ),
        migrations.AlterModelTable(
            name='qmnumbersequence',
            table='planning_qmnumbersequence',
        ),
        migrations.AlterModelTable(
            name='qualitymaintenance',
            table='planning_qualitymaintenance',
        ),
        migrations.AlterModelTable(
            name='qualitymaintenanceinstance',
            table='planning_qualitymaintenanceinstance',
        ),
        migrations.AlterModelTable(
            name='qualitymaintenancestep',
            table='planning_qualitymaintenancestep',
        ),
    ]
