# Generated by Django 6.0.2 on 2026-04-12 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_rename_single_interval_meter_qualitymaintenance_single_interval_value_and_more'),
        ('work_orders', '0004_workorder_hot_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualitymaintenanceinstance',
            name='work_order_id',
        ),
        migrations.AddField(
            model_name='qualitymaintenanceinstance',
            name='work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qm_instances', to='work_orders.workorder'),
        ),
    ]
