# Generated by Django 6.0.4 on 2026-05-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_qualitymaintenancedocument_single_interval_parts_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualitymaintenancedocument',
            name='single_interval_value',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='qualitymaintenancedocumentstep',
            name='interval_value',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='qualitymaintenanceplan',
            name='meter_start',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True),
        ),
    ]
