# Generated by Django 6.0.2 on 2026-04-16 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_remove_qualitymaintenanceinstance_work_order_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QMNumberSequence',
        ),
    ]
