# Generated by Django 6.0.2 on 2026-04-16 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0004_delete_qmnumbersequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualitymaintenance',
            name='manual_checklist',
            field=models.FileField(blank=True, null=True, upload_to='qm_checklists/'),
        ),
    ]
