# Generated by Django 6.0.2 on 2026-04-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0005_qualitymaintenance_manual_checklist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualitymaintenance',
            name='manual_checklist',
        ),
        migrations.AddField(
            model_name='qualitymaintenancestep',
            name='step_checklist',
            field=models.FileField(blank=True, null=True, upload_to='qm_checklists/'),
        ),
    ]
