# Generated by Django 6.0.2 on 2026-04-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0006_remove_qualitymaintenance_manual_checklist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualitymaintenance',
            name='single_interval_checklist',
            field=models.FileField(blank=True, null=True, upload_to='qm_checklists/'),
        ),
    ]
