# Generated by Django 6.0.2 on 2026-04-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0007_qualitymaintenance_single_interval_checklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualitymaintenance',
            name='est_work_hours',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='qualitymaintenancestep',
            name='est_work_hours',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
        ),
    ]
