# Generated by Django 6.0.4 on 2026-05-29 15:58

import django.db.models.deletion
import moc.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EffValRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('EFFORT', 'Effort'), ('VALUE', 'Value')], max_length=10)),
                ('source_field', models.CharField(max_length=50)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='MOC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moc_number', models.CharField(default=moc.models.generate_moc_number, max_length=12, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_completed', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Deferred', 'Deferred'), ('In Progress', 'In Progress'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], max_length=12)),
                ('define_change', models.TextField(blank=True)),
                ('anticipated_outcome', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MOCQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('safety', 'Safety & Health'), ('documentation', 'Documentation'), ('education', 'Education'), ('procurement', 'Procurement'), ('data_tech', 'Data & Technology'), ('test_imp', 'Test & Implementation'), ('social', 'Social')], max_length=30)),
                ('text', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='EffValPointRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_key', models.CharField(max_length=20)),
                ('points', models.IntegerField()),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranges', to='moc.effvalrule')),
            ],
            options={
                'ordering': ['value_key'],
            },
        ),
        migrations.CreateModel(
            name='MOCAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='moc_attachments/')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('moc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='moc.moc')),
            ],
        ),
        migrations.CreateModel(
            name='MOCCon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=500, null=True)),
                ('moc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cons', to='moc.moc')),
            ],
        ),
        migrations.CreateModel(
            name='MOCConsiderations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setup_months', models.CharField(blank=True, choices=[('0-6', '0-6'), ('7-12', '7-12'), ('13-18', '13-18'), ('19-24', '19-24'), ('>24', '>24')], max_length=10)),
                ('implementation_months', models.CharField(blank=True, choices=[('0-3', '0-3'), ('4-6', '4-6'), ('7-9', '7-9'), ('10-12', '10-12'), ('>12', '>12')], max_length=10)),
                ('contractor_hours', models.CharField(blank=True, choices=[('0-50', '0-50'), ('51-100', '51-100'), ('101-200', '101-200'), ('201-300', '201-300'), ('>300', '>300')], max_length=12)),
                ('eq_downtime', models.CharField(blank=True, choices=[('0-6', '0-6'), ('7-12', '7-12'), ('13-18', '13-18'), ('19-24', '19-24'), ('>24', '>24')], max_length=10)),
                ('warranty_impact', models.CharField(blank=True, choices=[('None', 'None'), ('Low', 'Low'), ('Med', 'Med'), ('High', 'High')], max_length=10)),
                ('project_cost', models.CharField(blank=True, choices=[('0', '0'), ('1-5000', '1-5000'), ('5001-10000', '5001-10000'), ('10001-50000', '10001-50000'), ('>50000', '>50000')], max_length=20)),
                ('savings_confirmed', models.CharField(blank=True, choices=[('0-10000', '0-10000'), ('10001-50000', '10001-50000'), ('50001-75000', '50001-75000'), ('75001-100000', '75001-100000'), ('>100000', '>100000')], max_length=20)),
                ('savings_soft', models.CharField(blank=True, choices=[('0-10000', '0-10000'), ('10001-50000', '10001-50000'), ('50001-75000', '50001-75000'), ('75001-100000', '75001-100000'), ('>100000', '>100000')], max_length=20)),
                ('inventory_cost', models.CharField(blank=True, choices=[('0', '0'), ('1-5000', '1-5000'), ('5001-10000', '5001-10000'), ('10001-50000', '10001-50000'), ('>50000', '>50000')], max_length=20)),
                ('production_gain', models.CharField(blank=True, choices=[('0-5', '0-5'), ('6-10', '6-10'), ('11-15', '11-15'), ('16-20', '16-20'), ('>20', '>20')], max_length=20)),
                ('safety_gain', models.CharField(blank=True, choices=[('None', 'None'), ('Low', 'Low'), ('Med', 'Med'), ('High', 'High')], max_length=10)),
                ('social_impact', models.CharField(blank=True, choices=[('None', 'None'), ('Low', 'Low'), ('Med', 'Med'), ('High', 'High')], max_length=10)),
                ('roi_months', models.CharField(blank=True, choices=[('0-3', '0-3'), ('4-6', '4-6'), ('7-9', '7-9'), ('10-12', '10-12'), ('>12', '>12')], max_length=10)),
                ('moc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='considerations', to='moc.moc')),
            ],
        ),
        migrations.CreateModel(
            name='MOCEffValPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effort', models.FloatField()),
                ('value', models.FloatField()),
                ('ratio', models.FloatField(blank=True, null=True)),
                ('moc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effval', to='moc.moc')),
            ],
        ),
        migrations.CreateModel(
            name='MOCPro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=500, null=True)),
                ('moc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pros', to='moc.moc')),
            ],
        ),
        migrations.CreateModel(
            name='MOCQuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dropdown_answer', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], max_length=6)),
                ('detail', models.TextField(blank=True)),
                ('complete', models.BooleanField(default=False)),
                ('moc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='moc.moc')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='moc.mocquestion')),
            ],
        ),
        migrations.CreateModel(
            name='Safety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sh_risk', models.CharField(blank=True, choices=[('0', '0'), ('5', '5'), ('10', '10'), ('25', '25'), ('35', '35'), ('50', '50')], max_length=4)),
                ('sh_freq', models.CharField(blank=True, choices=[('0', '0'), ('2', '2'), ('4', '4'), ('6', '6'), ('8', '8'), ('10', '10')], max_length=4)),
                ('env_risk', models.CharField(blank=True, choices=[('0', '0'), ('5', '5'), ('10', '10'), ('25', '25'), ('35', '35'), ('50', '50')], max_length=4)),
                ('env_freq', models.CharField(blank=True, choices=[('0', '0'), ('2', '2'), ('4', '4'), ('6', '6'), ('8', '8'), ('10', '10')], max_length=4)),
                ('fin_risk', models.CharField(blank=True, choices=[('0', '0'), ('5', '5'), ('10', '10'), ('25', '25'), ('35', '35'), ('50', '50')], max_length=4)),
                ('fin_freq', models.CharField(blank=True, choices=[('0', '0'), ('2', '2'), ('4', '4'), ('6', '6'), ('8', '8'), ('10', '10')], max_length=4)),
                ('soc_risk', models.CharField(blank=True, choices=[('0', '0'), ('5', '5'), ('10', '10'), ('25', '25'), ('35', '35'), ('50', '50')], max_length=4)),
                ('soc_freq', models.CharField(blank=True, choices=[('0', '0'), ('2', '2'), ('4', '4'), ('6', '6'), ('8', '8'), ('10', '10')], max_length=4)),
                ('moc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='safety', to='moc.moc')),
            ],
        ),
    ]
