# Generated by Django 6.0.2 on 2026-04-19 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0016_alter_machineshiftstatus_available'),
        ('work_orders', '0007_alter_workorder_troubleshoot_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortTermCM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('problem', models.CharField(max_length=255)),
                ('corrective_action', models.CharField(max_length=255)),
                ('due_date', models.DateField()),
                ('progress', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Complete', 'Complete'), ('Canceled', 'Canceled')], max_length=15)),
                ('completed_date', models.DateField()),
                ('complete', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=15)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shortterm_equipment', to='equipment.equipment')),
                ('equipment_desc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shortterm_eq_desc', to='equipment.equipment')),
                ('repair_desc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shortterm_rep_desc', to='work_orders.workorder')),
                ('troubleshoot_desc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shortterm_ts_desc', to='work_orders.workorder')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shortterm_wo', to='work_orders.workorder')),
            ],
        ),
    ]
