# Generated by Django 6.0.2 on 2026-04-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condition_monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorttermcm',
            name='equipment_desc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shorttermcm',
            name='repair_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shorttermcm',
            name='troubleshoot_desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
