# Generated by Django 6.0.2 on 2026-04-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condition_monitoring', '0002_alter_shorttermcm_equipment_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorttermcm',
            name='completed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
