# Generated by Django 6.0.4 on 2026-05-17 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condition_monitoring', '0003_alter_shorttermcm_completed_date'),
        ('equipment', '0019_alter_component_wty_uom'),
        ('work_orders', '0015_workorder_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='MagPlug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meter_reading', models.IntegerField(blank=True, null=True)),
                ('compartment', models.CharField(blank=True, choices=[('Engine', 'Engine'), ('Transmission', 'Transmission'), ('Trans Mag Strain', 'Trans Mag Strain'), ('Upbox', 'Upbox'), ('Dropbox', 'Dropbox'), ('Hydraulic', 'Hydraulic'), ('Front Diff', 'Front Diff'), ('Centre Diff', 'Centre Diff'), ('Rear Diff', 'Rear Diff')], null=True)),
                ('plug_rating', models.IntegerField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], null=True)),
                ('comments', models.CharField(blank=True, max_length=255, null=True)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mag_plug_eq', to='equipment.equipment')),
                ('meter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mag_plug_mtr', to='equipment.meter')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mag_plug_wo', to='work_orders.workorder')),
            ],
        ),
    ]
