# Generated by Django 6.0.4 on 2026-05-18 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condition_monitoring', '0004_magplug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magplug',
            name='plug_rating',
            field=models.IntegerField(blank=True, choices=[(1, '1 - Excellent'), (2, '2 - Good'), (3, '3 - Fair'), (4, '4 - Poor'), (5, '5 - Critical Failure')], null=True),
        ),
    ]
