# Generated by Django 6.0.4 on 2026-05-18 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condition_monitoring', '0006_filterrating'),
        ('equipment', '0019_alter_component_wty_uom'),
        ('work_orders', '0015_workorder_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValveSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meter_reading', models.IntegerField(blank=True, null=True)),
                ('comments', models.CharField(blank=True, max_length=255, null=True)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valve_sets', to='equipment.equipment')),
                ('meter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valve_sets', to='equipment.meter')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valve_sets', to='work_orders.workorder')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ValveSetReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cylinder_number', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], max_length=2, null=True)),
                ('int_exh', models.CharField(blank=True, choices=[('Int', 'Intake'), ('Exh', 'Exhaust')], max_length=3, null=True)),
                ('valve_number', models.CharField(blank=True, choices=[('1A', '1A'), ('1B', '1B'), ('2A', '2A'), ('2B', '2B'), ('3A', '3A'), ('3B', '3B'), ('4A', '4A'), ('4B', '4B'), ('5A', '5A'), ('5B', '5B'), ('6A', '6A'), ('6B', '6B'), ('7A', '7A'), ('7B', '7B'), ('8A', '8A'), ('8B', '8B')], max_length=2, null=True)),
                ('valve_setting', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('valve_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='condition_monitoring.valveset')),
            ],
            options={
                'ordering': ['cylinder_number', 'int_exh', 'valve_number'],
            },
        ),
    ]
