# Generated by Django 6.0.4 on 2026-05-18 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condition_monitoring', '0007_valveset_valvesetreading'),
        ('equipment', '0019_alter_component_wty_uom'),
        ('work_orders', '0015_workorder_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='CylinderTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meter_reading', models.IntegerField(blank=True, null=True)),
                ('comments', models.CharField(blank=True, max_length=255, null=True)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cylinder_temps', to='equipment.equipment')),
                ('meter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cylinder_temps', to='equipment.meter')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cylinder_temps', to='work_orders.workorder')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CylinderTempReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cylinder_number', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], max_length=2, null=True)),
                ('temp_reading', models.CharField(blank=True, max_length=4, null=True)),
                ('uom', models.CharField(blank=True, choices=[('degrees C', 'degrees C'), ('degrees F', 'degrees F')], max_length=10, null=True)),
                ('cylinder_temp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cyl_temp_readings', to='condition_monitoring.cylindertemp')),
            ],
            options={
                'ordering': ['cylinder_number', 'temp_reading', 'uom'],
            },
        ),
    ]
