# Generated by Django 6.0.4 on 2026-05-19 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condition_monitoring', '0008_cylindertemp_cylindertempreading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cylindertempreading',
            name='cylinder_number',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('Turbo', 'Turbo')], max_length=6, null=True),
        ),
    ]
