# Generated by Django 6.0.4 on 2026-05-19 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condition_monitoring', '0009_alter_cylindertempreading_cylinder_number'),
        ('equipment', '0019_alter_component_wty_uom'),
        ('work_orders', '0015_workorder_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='BucketLip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meter_reading', models.IntegerField(blank=True, null=True)),
                ('comments', models.CharField(blank=True, max_length=255, null=True)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bucket_lips', to='equipment.equipment')),
                ('meter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bucket_lips', to='equipment.meter')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bucket_lips', to='work_orders.workorder')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LipMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_side', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('right_side', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('centre', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('bucket_lip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lip_measurements', to='condition_monitoring.bucketlip')),
            ],
            options={
                'ordering': ['left_side', 'right_side', 'centre'],
            },
        ),
    ]
