# Generated by Django 6.0.4 on 2026-05-19 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condition_monitoring', '0010_bucketlip_lipmeasurement'),
        ('equipment', '0019_alter_component_wty_uom'),
        ('work_orders', '0015_workorder_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxLiner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meter_reading', models.IntegerField(blank=True, null=True)),
                ('comments', models.CharField(blank=True, max_length=255, null=True)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='box_liners', to='equipment.equipment')),
                ('meter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='box_liners', to='equipment.meter')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='box_liners', to='work_orders.workorder')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LinerMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, choices=[('Pos 1', 'Pos 1'), ('Pos 2', 'Pos 2'), ('Pos 3', 'Pos 3'), ('Pos 4', 'Pos 4'), ('Pos 5', 'Pos 5'), ('Pos 6', 'Pos 6'), ('Pos 7', 'Pos 7'), ('Pos 8', 'Pos 8'), ('Pos 9', 'Pos 9'), ('Pos 10', 'Pos 10'), ('Pos 11', 'Pos 11'), ('Pos 12', 'Pos 12'), ('Pos 13', 'Pos 13')], max_length=6, null=True)),
                ('pos_reading', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('box_liner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liner_measurements', to='condition_monitoring.boxliner')),
            ],
            options={
                'ordering': ['position', 'pos_reading'],
            },
        ),
    ]
