# Generated by Django 6.0.4 on 2026-05-19 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condition_monitoring', '0011_boxliner_linermeasurement'),
        ('equipment', '0019_alter_component_wty_uom'),
        ('work_orders', '0015_workorder_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='CycleTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meter_reading', models.IntegerField(blank=True, null=True)),
                ('comments', models.CharField(blank=True, max_length=255, null=True)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cycle_times', to='equipment.equipment')),
                ('meter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cycle_times', to='equipment.meter')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cycle_times', to='work_orders.workorder')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CycleTimeMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(blank=True, choices=[('Steering', 'Steering'), ('Ejector', 'Ejector'), ('Lift', 'Lift'), ('Tilt', 'Tilt'), ('Boom', 'Boom'), ('Stick', 'Stick'), ('Turret', 'Turret'), ('Telescopic', 'Telescopic'), ('House', 'House'), ('Scissor', 'Scissor'), ('Drill Feed', 'Drill Feed'), ('Bolt Feed', 'Bolt Feed'), ('Boom Feed', 'Boom Feed')], max_length=50, null=True)),
                ('position', models.CharField(blank=True, choices=[('Left', 'Left'), ('Right', 'Right'), ('Up', 'Up'), ('Down', 'Down'), ('Tilt', 'Tilt'), ('Rollback', 'Rollback'), ('Extend', 'Extend'), ('Retract', 'Retract'), ('Swing/Rotate CW', 'Swing/Rotate CW'), ('Swing/Rotate CCW', 'Swing/Rotate CCW'), ('In', 'Int'), ('Out', 'Out')], max_length=50, null=True)),
                ('time', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('cycle_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_time_measurements', to='condition_monitoring.cycletime')),
            ],
            options={
                'ordering': ['system', 'time'],
            },
        ),
    ]
