# Generated by Django 6.0.4 on 2026-05-20 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condition_monitoring', '0012_cycletime_cycletimemeasurement'),
        ('equipment', '0019_alter_component_wty_uom'),
    ]

    operations = [
        migrations.CreateModel(
            name='TireInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tire_size', models.CharField(blank=True, max_length=50, null=True)),
                ('tire_face', models.CharField(blank=True, max_length=50, null=True)),
                ('tread_depth_new', models.IntegerField(blank=True, null=True)),
                ('inflation_pressure', models.IntegerField(blank=True, null=True)),
                ('asset_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tire_info_asset', to='equipment.equipment')),
                ('equipment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tire_info_eq', to='equipment.equipment')),
                ('make', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tire_info_make', to='equipment.equipment')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tire_info_model', to='equipment.equipment')),
            ],
        ),
    ]
