# Generated by Django 6.0.4 on 2026-05-20 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condition_monitoring', '0013_tireinformation'),
        ('equipment', '0019_alter_component_wty_uom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tireinformation',
            name='asset_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tire_info_asset', to='equipment.assettype'),
        ),
        migrations.AlterField(
            model_name='tireinformation',
            name='equipment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tire_info_eq', to='equipment.eq_type'),
        ),
    ]
