# Generated by Django 6.0.4 on 2026-05-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condition_monitoring', '0014_alter_tireinformation_asset_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tireinformation',
            name='make',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tireinformation',
            name='model',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
