# Generated by Django 6.0.4 on 2026-05-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condition_monitoring', '0015_alter_tireinformation_make_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tireinformation',
            name='tire_face',
            field=models.CharField(blank=True, choices=[('Smooth', 'Smooth'), ('Treaded', 'Treaded')], max_length=50, null=True),
        ),
    ]
