# Generated by Django 6.0.4 on 2026-05-21 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condition_monitoring', '0016_alter_tireinformation_tire_face'),
        ('equipment', '0019_alter_component_wty_uom'),
        ('work_orders', '0015_workorder_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='TireChangeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tire_id_off', models.CharField(blank=True, max_length=50, null=True)),
                ('tire_id_on', models.CharField(blank=True, max_length=50, null=True)),
                ('position', models.CharField(blank=True, max_length=50, null=True)),
                ('tread_depth_off', models.IntegerField(blank=True, null=True)),
                ('tread_depth_on', models.IntegerField(blank=True, null=True)),
                ('rim_id_off', models.CharField(blank=True, max_length=50, null=True)),
                ('rim_id_on', models.CharField(blank=True, max_length=50, null=True)),
                ('reason_for_failure', models.CharField(blank=True, max_length=255, null=True)),
                ('inflation_pressure', models.IntegerField(blank=True, null=True)),
                ('scrapped', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True)),
                ('recapped', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TireChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meter_reading', models.IntegerField(blank=True, null=True)),
                ('comments', models.CharField(blank=True, max_length=255, null=True)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tire_changes', to='equipment.equipment')),
                ('meter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tire_changes', to='equipment.meter')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tire_changes', to='work_orders.workorder')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TireFailure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failure_mode', models.CharField(blank=True, max_length=50, null=True)),
                ('tire_change_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tire_failures', to='condition_monitoring.tirechangeinfo')),
            ],
        ),
        migrations.AddField(
            model_name='tirechangeinfo',
            name='scrap_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tire_changes', to='condition_monitoring.tirefailure'),
        ),
    ]
