# Generated by Django 6.0.4 on 2026-05-21 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condition_monitoring', '0017_tirechangeinfo_tirechange_tirefailure_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tirefailure',
            name='tire_change_info',
        ),
    ]
