# Generated by Django 6.0.4 on 2026-05-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condition_monitoring', '0018_remove_tirefailure_tire_change_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tirechangeinfo',
            name='position',
            field=models.CharField(blank=True, choices=[('Front Left', 'Front Left'), ('Front Right', 'Front Right'), ('Centre Left', 'Centre Left'), ('Centre Right', 'Centre Right'), ('Centre Outside Left', 'Centre Outside Left'), ('Centre Outside Right', 'Centre Outside Right'), ('Centre Inside Left', 'Centre Inside Left'), ('Centre Inside Right', 'Centre Inside Right'), ('Rear Left', 'Rear Left'), ('Rear Right', 'Rear Right'), ('Rear Outside Left', 'Rear Outside Left'), ('Rear Outside Right', 'Rear Outside Right'), ('Rear Inside Left', 'Rear Inside Left'), ('Rear Inside Right', 'Rear Inside Right')], max_length=50, null=True),
        ),
    ]
