# Generated by Django 6.0.4 on 2026-05-21 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condition_monitoring', '0019_alter_tirechangeinfo_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='tirechangeinfo',
            name='tire_change',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tire_change_info', to='condition_monitoring.tirechange'),
            preserve_default=False,
        ),
    ]
