# Generated by Django 6.0.4 on 2026-05-21 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condition_monitoring', '0020_tirechangeinfo_tire_change'),
        ('purchasing', '0006_purchase_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='tirechangeinfo',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tire_changes', to='purchasing.purchase'),
        ),
        migrations.AlterField(
            model_name='tirechangeinfo',
            name='reason_for_failure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tire_changes_failure', to='condition_monitoring.tirefailure'),
        ),
        migrations.AlterField(
            model_name='tirechangeinfo',
            name='scrap_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tire_changes_scrap', to='condition_monitoring.tirefailure'),
        ),
    ]
