# Generated by Django 6.0.4 on 2026-05-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condition_monitoring', '0021_tirechangeinfo_purchase_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tirechangeinfo',
            name='reason_for_failure',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tirechangeinfo',
            name='scrap_reason',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
