# Generated by Django 6.0.4 on 2026-05-21 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condition_monitoring', '0022_alter_tirechangeinfo_reason_for_failure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tirechangeinfo',
            name='reason_for_failure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tire_changes_failure', to='condition_monitoring.tirefailure'),
        ),
        migrations.AlterField(
            model_name='tirechangeinfo',
            name='scrap_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tire_changes_scrap', to='condition_monitoring.tirefailure'),
        ),
    ]
