# Generated by Django 6.0.4 on 2026-05-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condition_monitoring', '0024_tireinspection_tireinspectionreading'),
    ]

    operations = [
        migrations.CreateModel(
            name='RimInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_tested', models.DateField()),
                ('pass_fail', models.CharField(blank=True, choices=[('Pass', 'Pass'), ('Fail', 'Fail')], max_length=4, null=True)),
                ('failure_reason', models.CharField(blank=True, choices=[('Bent', 'Bent'), ('Cracked', 'Cracked'), ('Corroded', 'Corroded'), ('Excessive Wear', 'Excessive Wear'), ('Centre Plate Damage', 'Centre Plate Damage'), ('Run Flat', 'Run Flat'), ('Lock Ring Groove Failure', 'Lock Ring Groove Failure'), ('Gutter Section Failure', 'Gutter Section Failure'), ('Other', 'Other')], max_length=50, null=True)),
                ('next_test_date', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'ordering': ['-date_tested', '-id'],
            },
        ),
    ]
