# Generated by Django 6.0.4 on 2026-05-23 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condition_monitoring', '0025_riminspection'),
    ]

    operations = [
        migrations.AddField(
            model_name='riminspection',
            name='rim_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
