# Generated by Django 6.0.4 on 2026-05-23 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condition_monitoring', '0026_riminspection_rim_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tireinformation',
            name='tire_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
