# Generated by Django 6.0.4 on 2026-05-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condition_monitoring', '0027_tireinformation_tire_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riminspection',
            name='pass_fail',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Pass', 'Pass'), ('Fail', 'Fail')], max_length=4, null=True),
        ),
    ]
