# Generated by Django 6.0.4 on 2026-05-23 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condition_monitoring', '0028_alter_riminspection_pass_fail'),
    ]

    operations = [
        migrations.AddField(
            model_name='riminspection',
            name='last_test_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riminspection',
            name='number_of_tests',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
