# Generated by Django 6.0.4 on 2026-05-23 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condition_monitoring', '0029_riminspection_last_test_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tirechangeinfo',
            name='tire_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
