# Generated by Django 6.0.4 on 2026-05-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condition_monitoring', '0030_tirechangeinfo_tire_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valvesetreading',
            name='valve_number',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=2, null=True),
        ),
    ]
